[docker] fixes #134 - Modify Dockerfile to fix sqlite problem
skycoin/skywire-testnet pull request #135
Opened 2018-08-27 21:49 UTC by stdevNorge

Fixes #134 

Changes:
- Update to golang 1.10
- Install some dependencies to Alpine
- Enable cgo 

Does this change need to mentioned in CHANGELOG.md?
No

2018-08-30 23:55 UTC, olemis requested changes

2018-08-30 23:55 UTC, olemis commented on hooks/push
> +# docker push $DOCKER_REPO:arm32v7
@stdevNorge in order to enable this images should be built upon `busybox`

2018-08-30 23:55 UTC, olemis commented on hooks/push
> +# docker push $DOCKER_REPO:arm64v8
This one should work with `alpine` image . What's wrong ?

2018-08-30 23:57 UTC, olemis commented on hooks/push
> +# docker push $DOCKER_REPO:arm64v8
You are building it and not publishing in the Hub ? Why ?

2018-09-04 04:27 UTC, gz-c commented
@olemis is this one good now?

2018-09-04 17:10 UTC, olemis requested changes
@gz-c the only thing missing is a comment in README about ARM base images `alpine` for `armv6`, `arm64v8` and `busybox` for `armv5`, `arm7`. @stdevNorge will get this done asap

2018-09-04 17:13 UTC, olemis commented
@gz-c ARM builds working as expected . See [unofficial image repository tags](https://hub.docker.com/r/simelotech/skywire/tags/).

2018-09-05 00:55 UTC, olemis commented
@gz-c English and Spanish README are complete . Maybe we'll need an update for other languages as well . Other than this I'd only suggest to wait for the Docker Cloud build triggered by latest commits. If they succeed it's ready to merge .

2018-09-06 04:53 UTC, merged