Made corrections to conform skycoin standards:
skycoin/skywire-testnet pull request #240
Opened 2019-03-20 17:06 UTC by ayuryshev

- https://github.com/skycoin/skycoin/wiki/Skycoin-project-Makefile-standards
- https://github.com/skycoin/skycoin/wiki/Skycoin-projects%27-Travis-CI-standards

2019-03-20 17:07 UTC, ayuryshev commented
```bash
$ make                                                                                                              20:05:35
check                          Run linters and tests
build                          Install dependencies, build apps and binaries. `go build` with ${OPTS} 
run                            Run skywire-node on host
stop                           Stop running skywire-node on host
clean                          Clean project: remove created binaries and apps
install                        Install `skywire-node`, `skywire-cli`, `manager-node`, `therealssh-cli`
lint                           Run linters. Use make install-linters first
install-linters                Install linters
format                         Formats the code. Must have goimports installed (use make install-linters).
dep                            Sorts dependencies
host-apps                      Build apps binaries 
bin                            Build `skywire-node`, `skywire-cli`, `manager-node`, `therealssh-cli`
docker-image                   Build docker image `skywire-runner`
docker-clean                   Clean docker system: remove container ${DOCKER_NODE} and network ${DOCKER_NETWORK}
docker-network                 Create docker network ${DOCKER_NETWORK}
docker-apps                    Build apps binaries for dockerized skywire-node. `go build` with  ${DOCKER_OPTS}
docker-bin                     Build `skywire-node`, `skywire-cli`, `manager-node`, `therealssh-cli`. `go build` with  ${DOCKER_OPTS}
docker-volume                  Prepare docker volume for dockerized skywire-node
docker-run                     Run dockerized skywire-node ${DOCKER_NODE} in image ${DOCKER_IMAGE} with network ${DOCKER_NETWORK}
docker-stop                    Stop running dockerized skywire-node ${DOCKER_NODE}
```

2019-03-21 07:29 UTC, evanlinjin approved these changes
Perfect. Just change the gramatical error.

2019-03-21 07:29 UTC, evanlinjin commented on Makefile
> +host-apps: ## Build apps binaries
Change to `## Build app binaries`

2019-03-21 07:34 UTC, evanlinjin commented on .travis.yml
> -  - make test
We need to run tests. Please keep this.

2019-03-21 07:35 UTC, evanlinjin requested changes

2019-03-21 07:35 UTC, evanlinjin commented on Makefile
> -test: ## Run tests for net
We need to run go tests. Where are they now?

2019-03-21 08:02 UTC, ayuryshev commented on Makefile
> +host-apps: ## Build apps binaries
Done

2019-03-21 08:21 UTC, ayuryshev commented on Makefile
> -test: ## Run tests for net
Returned:
```
test: ## Run tests for net
        ${OPTS} go test -race -tags no_ci -cover -timeout=5m ./internal/...
        ${OPTS} go test -race -tags no_ci -cover -timeout=5m ./pkg/...
```

2019-03-21 08:23 UTC, evanlinjin approved these changes

2019-03-21 08:23 UTC, merged