[WIP] TestingProposals-241
skycoin/skywire-testnet pull request #242
Opened 2019-03-25 07:27 UTC by ayuryshev

I'm publishing right now results to review and discuss

1. TestingProposals.md - the doc which I started, personally I think
that second doc is better for us - it's more specific for skywire
2. PeriodicTableOfTests.md - it's more concentrated on measurement and
decision support
3. periodic-table-of-tests.zsh - is a POC, how to create measurements. It's only for illustration purposes

Closes: #241

2019-03-28 06:52 UTC, evanlinjin requested changes
Everything that is not commented on by me, I completely agree with.

2019-03-28 06:52 UTC, evanlinjin commented on TestingProposals.md
> +- easily integrated with IDEs, etc
Not priority.

2019-03-28 06:52 UTC, evanlinjin commented on TestingProposals.md
> +- it could be 2-3 nodes  in one-two networks
We need to be able to easily configure the number of nodes/services for the local network.

2019-03-28 06:52 UTC, evanlinjin commented on TestingProposals.md
> +**Developer environment**:
There should be two types of developer environments:
1. Local environment (all services and the entire Skywire network runs locally).
2. Public environment (all services except `skywire-node` runs on public servers).

2019-03-28 06:52 UTC, evanlinjin commented on periodic-table-of-tests.zsh
> +#!/bin/zsh
Not needed.

2019-03-28 06:52 UTC, evanlinjin commented on PeriodicTableOfTests.md
> +# "Periodic Table of Tests"
Not needed.

2019-04-03 07:00 UTC, jdknives requested changes
Needs to be merged into skywire-specs rather.

2019-04-03 07:24 UTC, closed without merging