Apps create multiple transports-248
skycoin/skywire-testnet pull request #252
Opened 2019-03-28 05:24 UTC by ayuryshev

Changes:

1. pkg/transport/manager.go: instead of empy uuid, now it uses namebased uuid based on remote pk.  This prevents creation of double transports

Test:

Run in sepate shells:
NodeA: `make docker-run`
NodeB: `./skywire-cli config && make run`
Third shell: 
```
$  ./skywire-cli add-transport $SW_NODE_B_PK   # repeat this several times
$ ./skywire-cli list-transports
```
It must return only one row. (In current branch it creates duplicate transports)

Closes: #248

2019-03-28 06:44 UTC, evanlinjin requested changes
We need to give this problem some more thought.

2019-03-28 06:44 UTC, evanlinjin commented on pkg/transport/manager.go
> +	uid := uuid.NewSHA1(uuid.UUID{}, []byte(remote.Hex()))
This implementation is problematic because Transport IDs are used **globally** to identify the transport and a transport is a bi-directional communication between two nodes.

Refer to specs: https://github.com/watercompany/skywire-specs/blob/master/Specifications.md#transport

2019-03-28 06:45 UTC, evanlinjin commented on pkg/transport/manager.go
> +	uid := uuid.NewSHA1(uuid.UUID{}, []byte(remote.Hex()))
if we combine the local and remote public keys, where we order the keys based on some factor... That might work.

2019-03-28 09:30 UTC, ayuryshev commented on pkg/transport/manager.go
> +	uid := uuid.NewSHA1(uuid.UUID{}, []byte(remote.Hex()))
Done

2019-03-28 10:22 UTC, evanlinjin requested changes

2019-03-28 10:22 UTC, evanlinjin commented on pkg/transport/manager.go
> +	uid := uuid.NewSHA1(uuid.UUID{}, append(tm.config.PubKey[:], remote[:]...))
If the remote is initiating the transport creation, the public keys will be the other way around. We should have an algorithm that puts one public key before another (some way of sorting).

2019-03-28 10:42 UTC, ivcosla commented on pkg/transport/manager.go
> +	uid := uuid.NewSHA1(uuid.UUID{}, append(tm.config.PubKey[:], remote[:]...))
I think that may work, just having both PKs always in the same order, no matter who is initiating, but yes, we need to consider it carefully.

2019-03-28 11:09 UTC, ayuryshev commented on pkg/transport/manager.go
> +	uid := uuid.NewSHA1(uuid.UUID{}, append(tm.config.PubKey[:], remote[:]...))
Confirmed:
```
 ./skywire-cli add-transport $SW_NODE_B_PK  
 ./skywire-cli --rpc $SW_NODE_B:3435 add-transport $SW_NODE_A_PK
```
Creates two records

2019-03-28 14:01 UTC, evanlinjin commented on Makefile
> +	-go clean -testcache
is this an extra `-` prepended? haha

2019-03-28 14:04 UTC, ayuryshev commented on Makefile
> +	-go clean -testcache
`-` is for continuing in case of errors

2019-04-03 06:34 UTC, evanlinjin reviewed
Good work so far. Just some tweaks to naming convention.

2019-04-03 06:34 UTC, evanlinjin commented on pkg/transport/manager.go
> +func GetTransportUUID(keyA, keyB cipher.PubKey, tpType string) uuid.UUID {
Rename to `MakeTransportID`.

2019-04-03 06:34 UTC, evanlinjin commented on pkg/transport/entry.go
> +	EdgesKeys [2]cipher.PubKey `json:"edges"`
Rename to `EdgeKeys`.

2019-04-04 00:31 UTC, evanlinjin requested changes
Beautiful work so far. Keep the changes coming!

2019-04-04 00:31 UTC, evanlinjin commented on pkg/transport/entry.go
> +func (se *SignedEntry) SetSignature(pk cipher.PubKey, secKey cipher.SecKey) {
Rename to `Sign`.

2019-04-04 00:31 UTC, evanlinjin commented on pkg/transport/entry.go
> +func (se *SignedEntry) Index(pk cipher.PubKey) byte {
I think it will be a good security measure to also compare `pk` with the other edge, and have a second output (of `error`), just in case of `pk` not equivalent to both edges.

2019-04-04 00:31 UTC, evanlinjin commented on pkg/transport/entry.go
> +func (se *SignedEntry) GetSignature(pk cipher.PubKey) cipher.Sig {
I think we should avoid the verb `Get` (as from my understanding, Golang convention suggests avoiding it). I think `Signature` will be fine here.

2019-04-04 00:31 UTC, evanlinjin commented on pkg/transport/handshake.go
>  		if err := json.NewEncoder(tr).Encode(sEntry); err != nil {
We may need to encode/decode into different structures. That way we can compare between the two, and ensure that only a signature is changed.

2019-04-04 00:31 UTC, evanlinjin commented on pkg/transport/manager.go
> +	return cipher.PubKey{}
Instead of returning an empty `cipher.PubKey`, consider returning an `error`. Thoughts @ayuryshev ?

2019-04-04 04:13 UTC, ayuryshev commented on pkg/transport/entry.go
> +func (se *SignedEntry) SetSignature(pk cipher.PubKey, secKey cipher.SecKey) {
Just `Sign`?
Actually I thought about limiting signing to just 2 operations: 
- on init
- on respond

and do nothing in case when signature is already set.

So maybe: InitSign - ResponseSign ?
Code will became more readable - possible errors will catch the eye immediately

Changing to Sign

2019-04-04 04:29 UTC, ayuryshev commented on pkg/transport/entry.go
> +func (se *SignedEntry) Index(pk cipher.PubKey) byte {
I thought about it.

It makes impossible to write in such way:

```go
sEntry.Signatures[sentry.Index(pk)]
```

I thought about alternatives:

- `(byte,error)` in result
- return an impossible value, e.g. `3` or '255' - must lead to "interesting" errors 
- and even `panic` (that thought was thrown away immediately)

So ..
It's easy to change - do so?

2019-04-04 04:29 UTC, ayuryshev commented on pkg/transport/entry.go
> +func (se *SignedEntry) GetSignature(pk cipher.PubKey) cipher.Sig {
Agreed

2019-04-04 04:37 UTC, ayuryshev commented on pkg/transport/manager.go
> +	return cipher.PubKey{}
It's the same as with `SignedEntry.Index()`

OK.

I will change to `(cipher.PubKey, error)` this
And `SignedEntry.Index()` to `(byte, error)`

It will make code a little bulkier but more "golangish".

2019-04-04 05:15 UTC, evanlinjin commented on pkg/transport/entry.go
> +func (se *SignedEntry) SetSignature(pk cipher.PubKey, secKey cipher.SecKey) {
I would prefer`SignAsResponder` and `SignAsInitiator`. Either that or a single function `Sign`.

2019-04-04 05:17 UTC, evanlinjin commented on pkg/transport/entry.go
> +func (se *SignedEntry) Index(pk cipher.PubKey) byte {
We don't need to write code like that. It's more important to handle errors and unexpected behaviors properly.

2019-04-04 05:18 UTC, evanlinjin commented on pkg/transport/manager.go
> +	return cipher.PubKey{}
"golangish" is the way of the Jedi. May the force be with you.

2019-04-04 08:43 UTC, ayuryshev commented on pkg/transport/handshake.go
>  		if err := json.NewEncoder(tr).Encode(sEntry); err != nil {
OK
I did exactly so in tests.
Here it remained as was before.
Agreed

2019-04-04 14:55 UTC, ivcosla commented
Seems to fail in an infinite loop when starting a node that previously had transports registered with `mainnet` branch.

Currently apps don't work. Loop creation fails with the following logs:

```
[2019-04-04T16:53:33+02:00] WARN [trmanager]: Failed to accept connection: Failed to recover pubkey from signature
[2019-04-04T16:54:34+02:00] INFO [router]: App request with type CreateLoop failed: route setup: rule setup: transport: deadline exceeded
```

2019-04-08 10:38 UTC, ivcosla commented on pkg/node/rpc.go
> +	if remote, Ok := tm.Remote(tp.Edges()); Ok == nil {
why not `ok` instead?

2019-04-08 10:38 UTC, ivcosla commented on pkg/node/rpc_client.go
> +		ID:     transport.MakeTransportID(mc.s.PubKey, remote, tpType),
I would name it `NewID`, since it's already a function of `transport` package.

2019-04-08 10:38 UTC, ivcosla commented on pkg/manager/user.go
> +	PwSalt []byte /*  */
Intended?

2019-04-08 10:38 UTC, ivcosla commented on pkg/messaging/client.go
> +	// edges [2]cipher.PubKey
Rather remove it than leave it commented, unless you have a reason

2019-04-08 10:38 UTC, ivcosla commented on pkg/messaging/client.go
> +		fmt.Printf("Dial with remote = %v\n", remote)
Debug comment?

2019-04-08 10:38 UTC, ivcosla commented on pkg/router/route_manager.go
> +	fmt.Println("got proto!")
same

2019-04-08 10:38 UTC, ivcosla commented on pkg/router/route_manager.go
>  		fmt.Println("err:", err)
here too

2019-04-08 10:38 UTC, ivcosla commented on pkg/transport/entry_test.go
> +func errorsPrint(errs ...error) {
a minor thing, but guess `printErrors` would be better

2019-04-08 10:38 UTC, ivcosla commented on pkg/transport/handshake.go
> +		// sEntry := &SignedEntry{Entry: entry, Signatures: [2]cipher.Sig{entry.Signature(tm.config.SecKey)}}
This should be removed

2019-04-08 10:38 UTC, ivcosla commented on pkg/transport/manager_test.go
> +	// errCh2 := make(chan error)
remove it

2019-04-08 10:38 UTC, ivcosla commented on pkg/transport/tcp_transport.go
> +	// lpk cipher.PubKey
same for these two

2019-04-08 10:38 UTC, ivcosla commented on pkg/transport/tcp_transport_test.go
> +	// assert.Equal(t, pk2, tr.Local())
again

2019-04-08 11:44 UTC, ayuryshev commented on pkg/node/rpc_client.go
> +		ID:     transport.MakeTransportID(mc.s.PubKey, remote, tpType),
`MakeTransportID` was an @evanlinjin  suggestion.
And in transport we have types:

- DiscoveryClient interface 
- Entry struct 
- EntryWithStatus struct 
- Factory interface 
- LogEntry struct 
- LogStore interface 
- ManagedTransport struct 
- Manager struct 
- ManagerConfig struct 
- MockFactory struct 
- MockTransport struct 
- PubKeyTable interface 
- SignedEntry struct 
- Status struct 
- TCPFactory struct 
- TCPTransport struct 
- Transport interface 

So I think `MakeTransportID` makes sense

2019-04-08 11:48 UTC, ayuryshev commented on pkg/manager/user.go
> +	PwSalt []byte /*  */
No. Clearing

2019-04-08 11:51 UTC, ayuryshev commented on pkg/messaging/client.go
> +		fmt.Printf("Dial with remote = %v\n", remote)
Clearing

2019-04-08 11:56 UTC, ayuryshev commented on pkg/transport/handshake.go
> +		// sEntry := &SignedEntry{Entry: entry, Signatures: [2]cipher.Sig{entry.Signature(tm.config.SecKey)}}
Yes

2019-04-08 11:57 UTC, ayuryshev commented on pkg/transport/manager_test.go
> +	// errCh2 := make(chan error)
Yes

2019-04-08 11:58 UTC, ayuryshev commented on pkg/transport/tcp_transport_test.go
> +	// assert.Equal(t, pk2, tr.Local())
yes again

2019-04-08 12:39 UTC, ayuryshev commented on pkg/node/rpc.go
> +	if remote, Ok := tm.Remote(tp.Edges()); Ok == nil {
It's already resolved

2019-04-08 12:42 UTC, ayuryshev commented on pkg/messaging/client.go
> +	// edges [2]cipher.PubKey
Yes

2019-04-08 12:42 UTC, ayuryshev commented on pkg/router/route_manager.go
>  		fmt.Println("err:", err)
Yes

2019-04-08 12:54 UTC, ayuryshev commented on pkg/transport/entry_test.go
> +func errorsPrint(errs ...error) {
It's almost stylistical.
What feels more natural: SVO or SOV?
So ..
It's used only one time - so I will make it anonimous:

```go
	doneCh := make(chan bool)
	go func(errs ...error) {
		for _, err := range errs {
			if err != nil {
				fmt.Println(err.Error())
			}
		}
		doneCh <- true
	}(errIdxA, errIdxB, errSigA, errSigB)

	<-doneCh
```

2019-04-08 12:55 UTC, ayuryshev commented on pkg/transport/manager_test.go
> +	// errCh2 := make(chan error)
Done

2019-04-08 13:15 UTC, evanlinjin requested changes
Looks really good. Please review my queries.

2019-04-08 13:15 UTC, evanlinjin commented on pkg/messaging/channel.go
> +func (c *channel) Edges() [2]cipher.PubKey {
We need a comment here.

2019-04-08 13:15 UTC, evanlinjin commented on pkg/transport/entry.go
> +func (e *Entry) SetEdges(edges [2]cipher.PubKey) {
Instead of `edges [2]cipher.PubKey` as input, I think `edge1, edge2 cipher.PubKey` would be clearer.

2019-04-08 13:15 UTC, evanlinjin commented on pkg/transport/entry.go
> +func (se *SignedEntry) Index(pk cipher.PubKey) (byte, error) {
Instead of returning an error, I think returning a boolean will make more sense. Take a note of it in the comments: "returns false if public key is not found".

2019-04-08 13:15 UTC, evanlinjin commented on pkg/transport/entry.go
> +func (se *SignedEntry) Sign(pk cipher.PubKey, secKey cipher.SecKey) error {
return a boolean. "Returns false if signature is not set".

2019-04-08 13:15 UTC, evanlinjin commented on pkg/transport/entry.go
> +func (se *SignedEntry) Signature(pk cipher.PubKey) (cipher.Sig, error) {
Return a boolean. "Returns false if no signature is found of given public key."

2019-04-08 13:15 UTC, evanlinjin commented on pkg/transport/handshake.go
> +		rcvdSEntry := &SignedEntry{}
maybe `respEntry` will be better?

2019-04-08 13:15 UTC, evanlinjin commented on pkg/transport/handshake.go
> +		rcvdSEntry := &SignedEntry{}
We also need to compare the sent Entry with the Received Entry and ensure no fields are modified.

2019-04-08 13:15 UTC, evanlinjin commented on pkg/transport/manager.go
> +func (tm *Manager) Remote(edges [2]cipher.PubKey) (cipher.PubKey, error) {
I would return `bool` instead of `error`.

2019-04-08 13:16 UTC, evanlinjin commented on pkg/transport/entry.go
> +func (e *Entry) SetEdges(edges [2]cipher.PubKey) {
Ignore this.

2019-04-08 13:19 UTC, evanlinjin commented on pkg/transport/entry_test.go
> +func errorsPrint(errs ...error) {
I think if we have a separate function, it would make the code easier to read.

2019-04-08 13:30 UTC, ayuryshev commented on pkg/transport/entry_test.go
> +func errorsPrint(errs ...error) {
This function is used just one time - that's the reason why I changed it anonimous function.

In case you propose to change it to named function - please propose name for it.
Be it: 
- printErrors
- errPrint
- eprint

I'm OK with each choice

2019-04-08 13:31 UTC, evanlinjin commented on pkg/transport/entry_test.go
> +func errorsPrint(errs ...error) {
`printErrors`. We can have it as a var within the function. `printErrors := func() ....`

2019-04-08 13:34 UTC, ayuryshev commented on pkg/messaging/channel.go
> +func (c *channel) Edges() [2]cipher.PubKey {
Yes
```
func (c *channel) Edges() [2]cipher.PubKey {
	// Edges returns the public keys of the Transport's edge nodes (should only have 2 edges and the least-significant edge should come first).
	return transport.SortPubKeys(c.link.Local(), c.remotePK)
}
```
It will be clearer this way

2019-04-08 13:36 UTC, evanlinjin commented on pkg/messaging/channel.go
> +func (c *channel) Edges() [2]cipher.PubKey {
It's golang standard to have a comment above each exposed function. I prefer we stick to the standard.

2019-04-08 13:42 UTC, ayuryshev commented on pkg/transport/entry.go
> +func (se *SignedEntry) Index(pk cipher.PubKey) (byte, error) {
We can follow the lead by standard libs and return `-1` instead of `error`.
E.g. <https://golang.org/pkg/strings/#Index>

Is it better?  - IDK

I can change it to do in such way

2019-04-08 13:43 UTC, ayuryshev commented on pkg/transport/entry.go
> +func (se *SignedEntry) Sign(pk cipher.PubKey, secKey cipher.SecKey) error {
OK

2019-04-08 13:43 UTC, ayuryshev commented on pkg/transport/entry.go
> +func (se *SignedEntry) Signature(pk cipher.PubKey) (cipher.Sig, error) {
OK

2019-04-08 13:44 UTC, evanlinjin commented on pkg/transport/entry.go
> +func (se *SignedEntry) Index(pk cipher.PubKey) (byte, error) {
> We can follow the lead by standard libs and return `-1` instead of `error`.
> E.g. https://golang.org/pkg/strings/#Index
> 
> Is it better? - IDK
> 
> I can change it to do in such way

Good idea. Yes.

2019-04-08 13:45 UTC, evanlinjin commented on pkg/transport/entry.go
> +func (se *SignedEntry) Index(pk cipher.PubKey) (byte, error) {
instead of `byte`, we will need `int8`.

2019-04-08 13:45 UTC, ayuryshev commented on pkg/transport/manager.go
> +func (tm *Manager) Remote(edges [2]cipher.PubKey) (cipher.PubKey, error) {
Again: maybe follow the lead by standard libs and return `-1`?

2019-04-08 13:52 UTC, evanlinjin commented on pkg/transport/manager.go
> +func (tm *Manager) Remote(edges [2]cipher.PubKey) (cipher.PubKey, error) {
I think we should stick to `bool`. As we are returning a `cipher.PubKey`.

2019-04-08 13:52 UTC, ayuryshev commented on pkg/transport/entry.go
> +func (se *SignedEntry) Index(pk cipher.PubKey) (byte, error) {
OK.
I'm changing it to `-1` logic - it will make code "lighter" in most cases and for rare cases we will need checks for `-1`
As with standard libs

2019-04-09 05:01 UTC, ayuryshev commented on pkg/transport/handshake.go
> +		rcvdSEntry := &SignedEntry{}
agreed for respEntry

We already have this check in `validateSignedEntry`:

```go
	if entry.Edges() != tr.Edges() {
		return errors.New("invalid entry edges")
	}
```

2019-04-09 05:14 UTC, ayuryshev commented on pkg/transport/manager.go
> +func (tm *Manager) Remote(edges [2]cipher.PubKey) (cipher.PubKey, error) {
Agreed
Such code looks more natural this way:
```go
	r.node.tm.WalkTransports(func(tp *transport.ManagedTransport) bool {
		if remote, ok := r.node.tm.Remote(tp.Edges()); ok {
			if typeIncluded(tp.Type()) && pkIncluded(r.node.tm.Local(), remote) {
				*out = append(*out, newTransportSummary(r.node.tm, tp, in.ShowLogs))
			}
			return true
		}
		return false
	})
```

2019-04-09 07:02 UTC, evanlinjin requested changes

2019-04-09 07:02 UTC, evanlinjin commented on pkg/messaging/channel.go
> +func (c *channel) Edges() [2]cipher.PubKey {
https://blog.golang.org/godoc-documenting-go-code

Please place the comment above the function. Thanks.

2019-04-09 07:02 UTC, evanlinjin commented on pkg/router/route_manager.go
>  		fmt.Println("err:", err)
Logging should be done via `github.com/skycoin/skycoin/src/util/logging`, not `fmt`.

2019-04-09 07:02 UTC, evanlinjin commented on pkg/transport/tcp_transport.go
> +	// lpk cipher.PubKey
Please fix this.

2019-04-09 08:39 UTC, ayuryshev commented on pkg/messaging/channel.go
> +func (c *channel) Edges() [2]cipher.PubKey {
Yes

2019-04-09 08:39 UTC, ayuryshev commented on pkg/transport/tcp_transport.go
> +	// lpk cipher.PubKey
Done

2019-04-09 08:40 UTC, ayuryshev commented on pkg/transport/tcp_transport.go
> +	// lpk cipher.PubKey
Done

2019-04-09 08:41 UTC, ayuryshev commented on pkg/messaging/channel.go
> +func (c *channel) Edges() [2]cipher.PubKey {
yes

2019-04-10 04:54 UTC, evanlinjin approved these changes
I have no way to test this code in an easy manner until the local testing environment is done. I will approve this now and deal with possible complications later. 🙂

Will merge after @ivcosla approves.

2019-04-15 08:18 UTC, merged