[WIP] Refactor 'skywire-cli'
skycoin/skywire-testnet pull request #267
Opened 2019-04-02 18:27 UTC by mungujn

I have restructured one command to show how I intend to go about resutructuring the rest of them @evanlinjin 
#264

2019-04-03 04:37 UTC, evanlinjin requested changes
Good work so far. Please review the requested changes.

2019-04-03 04:37 UTC, evanlinjin commented on cmd/skywire-cli/commands/node/pk.go
> +		client := commands.PrpcClient()
Golang does not allow for cyclic imports, so this here will not work.

I propose moving functions that depended by `/cmd/skywire-cli/commands` and any of `/cmd/skywire-cli/commands/<command>` folders, to `/cmd/skywire-cli/internal`.

Thoughts @ivcosla @mungujn @ayuryshev ?

2019-04-03 04:37 UTC, evanlinjin commented on cmd/skywire-cli/commands/root.go
> +func PrpcClient() node.RPCClient {
Prepending `P` to a function to highlight the function is public is not good Golang naming convention. If this was needed, I would name it `RPCClient`.

However, note that this function is only needed for `skywire-node`-specific commands. So I would move it within `/cmd/skywire-cli/node`.

2019-04-03 04:37 UTC, evanlinjin commented on cmd/skywire-cli/commands/node/node.go
> +var nodeCmd = &cobra.Command{
Rename `nodeCmd` to `RootCmd`. Note that we are to export this.

2019-04-03 04:37 UTC, evanlinjin commented on cmd/skywire-cli/commands/node/node.go
> +	commands.AddCommand(nodeCmd)
Have an `init()` function within `/cmd/skywire-cli/commands/root.go`, that adds `node.RootCmd` to `commands.RootCmd`.

2019-04-03 06:46 UTC, mungujn commented on cmd/skywire-cli/commands/root.go
> +func PrpcClient() node.RPCClient {
dont mind the P, just wanted to indicate my intent to make it public. but i see here thats not necessary

2019-04-03 06:58 UTC, mungujn commented on cmd/skywire-cli/commands/node/pk.go
> +		client := commands.PrpcClient()
Alright. Although package node imports commands but the commands package does not import node. to avoid that wrong import cycle the package main (in `/cmd/skywire-cli/commands`) is the one that imports node which registers its sub commands in its init function

2019-04-03 07:32 UTC, evanlinjin commented on cmd/skywire-cli/commands/node/pk.go
> +		client := commands.PrpcClient()
> Alright. Although package node imports commands but the commands package does not import node. to avoid that wrong import cycle the package main (in `/cmd/skywire-cli/commands`) is the one that imports node which registers its sub commands in its init function

I see. I had no idea that you can do that. But I would prefer if that `init` function is within `commands`.

2019-04-04 08:57 UTC, evanlinjin requested changes

2019-04-04 08:57 UTC, evanlinjin commented on cmd/skywire-cli/commands/mdisc/messaging.go
> +package mdisc
Rename file to `mdisc.go`.

2019-04-04 08:57 UTC, evanlinjin commented on cmd/skywire-cli/commands/mdisc/messaging.go
> +var MessageDiscoveryCmd = &cobra.Command{
Rename to `RootCmd`.

2019-04-04 08:57 UTC, evanlinjin commented on cmd/skywire-cli/commands/mdisc/messaging.go
>  	Run: func(_ *cobra.Command, args []string) {
Rename `mEntryCmd` to `entryCmd`.

2019-04-04 08:57 UTC, evanlinjin commented on cmd/skywire-cli/commands/mdisc/messaging.go
>  		ctx, cancel := context.WithTimeout(context.Background(), time.Second*10)
Rename `mAvailableServersCmd` to `availableServersCmd`.

2019-04-04 08:57 UTC, evanlinjin commented on cmd/skywire-cli/internal/internal.go
> +func RPCClient() node.RPCClient {
This is a `node`-specific method. Please move it to `commands/node` (alongside any relevant flags) and unexport it.

2019-04-04 08:57 UTC, evanlinjin commented on cmd/skywire-cli/internal/internal.go
> +func RPCClient() node.RPCClient {
Also note that any command that uses this is to go in `node`. Please modify accordingly.

2019-04-04 08:57 UTC, evanlinjin commented on cmd/skywire-cli/internal/internal.go
> +var rpcAddr string
What happened here?

2019-04-04 08:57 UTC, evanlinjin commented on cmd/skywire-cli/commands/rtfind/routing.go
> +package rtfind
rename to `rtfind.go`

2019-04-05 05:11 UTC, evanlinjin requested changes

2019-04-05 05:11 UTC, evanlinjin commented on cmd/skywire-cli/README.md
> +# CLI for skywire node
This is not needed.

2019-04-05 05:11 UTC, evanlinjin commented on cmd/skywire-cli/README.md
> +# CLI for skywire node
Please update `/README.md` to accommodate these changes.

2019-04-05 06:01 UTC, evanlinjin commented
#270

2019-04-05 06:01 UTC, closed without merging