[WIP] added rpc methods for procs
skycoin/skywire-testnet pull request #326
Opened 2019-05-01 16:16 UTC by ivcosla

Added methods to RPC and ProcManager.

2019-05-07 15:51 UTC, ivcosla commented on pkg/app/executor.go
> +type ExecutorFactory interface {
Previously, even if `Executor` was an interface there was no way to plug a different implementation of it into `Node`, since `NewExecutor` was always called inside to spawn new ones, thus I deemed necessary to create a factory that Nodes uses to spawn them, allowing other implementations of the factory, which allows to spawn different implementations of `Executor`.

2019-05-07 16:00 UTC, ivcosla commented on pkg/app/executor.go
> +	SetLogger(logger *logging.Logger)
Before we were creating new executors inside `procManager.RunProc` taking `*app.Meta` and `*app.ExecConfig` as arguments, and a logger was created per app for that executor (also passed as an argument).

Instead I wanted to pass an Executor as argument to RunProc, but needed a way to set such logger, as well as retrieving it, since such logger cannot be created before RunProc is called.

2019-05-08 02:53 UTC, evanlinjin requested changes
I'll complete this review at a later stage.

2019-05-08 02:53 UTC, evanlinjin commented on cmd/skywire-cli/commands/node/app.go
> +	Use:   "start-app <name> <port>",
`port` should be a flag and optional. No `--port` specified == use `0` as input for `StartProc` function.

2019-05-08 02:53 UTC, evanlinjin commented on pkg/node/config.go
> +	Port uint16   `json:"Port"`
Why did we change the tags here?

2019-05-08 07:10 UTC, ivcosla commented on cmd/skywire-cli/commands/node/app.go
> +	Use:   "start-app <name> <port>",
Ok, my mistake, thought we needed different ports every time, that's why I took it as argument.

2019-05-08 07:11 UTC, ivcosla commented on pkg/node/config.go
> +	Port uint16   `json:"Port"`
That was unintentional, some side effects of renaming.

2019-09-04 09:42 UTC, closed without merging