[WIP] Uptime tracking
skycoin/skywire-testnet pull request #328
Opened 2019-05-05 05:45 UTC by nkryuchkov

Closes https://github.com/watercompany/skywire-services/issues/17

Done:
- HTTP client for `uptime-tracker` 
- Generating config for `uptime-tracker`
- Sending uptime information to `uptime-tracker` in `skywire-node`
- Tests
- Documentation

2019-05-06 11:15 UTC, evanlinjin requested changes
Good work so far! Please review the requested changes. We await the integration test :)

2019-05-06 11:15 UTC, evanlinjin commented on cmd/skywire-node/commands/root.go
> +			for range ticker.C {
I would prefer if only this loop is in the go routine.

2019-05-06 11:15 UTC, evanlinjin commented on cmd/skywire-node/commands/root.go
> +	utClient "github.com/skycoin/skywire/internal/uptime-tracker/client"
Please rename `/internal/uptime-tracker/client` to `/internal/utclient`.

I know that this does not follow the current naming conventions. However, in the future we will name `messaging-discovery/client` to `mdclient`, `transport-discovery/client` to `tdclient`, etc (we don't need to touch this for now).

2019-05-06 11:15 UTC, evanlinjin commented on internal/uptime-tracker/client/client.go
> +	key    cipher.PubKey
`pk cipher.PubKey`
`sk cipher.SecKey`

This follows the Skywire conventions.

2019-05-06 11:15 UTC, evanlinjin commented on internal/uptime-tracker/client/client_test.go
> +		func(w http.ResponseWriter, r *http.Request) {
It is best not to use the `assert` and `require` libraries in go-routines. I would, here, create a channel of form `type reqCh chan http.Header` (or similar), and analyze the header elsewhere.

`type reqCh chan *http.Request` can work too.

2019-05-06 11:15 UTC, evanlinjin commented on internal/uptime-tracker/client/client_test.go
> +		assert.Equal(t, "/update", r.URL.String())
Refer to aforementioned.

2019-05-06 11:15 UTC, evanlinjin commented on internal/uptime-tracker/client/client_test.go
> +	err = c.UpdateNodeUptime(context.Background())
`context.TODO()` would be better here (as it is a test).

2019-05-06 12:40 UTC, evanlinjin approved these changes
Nice work!

2019-05-17 17:16 UTC, nkryuchkov commented
Will be merged after https://github.com/watercompany/skywire-services/pull/61

2019-05-29 13:43 UTC, merged