BUG: Ensure modules using internal/httpauth retries with correct nonce after 401.
skycoin/skywire-testnet pull request #349
Opened 2019-05-12 21:33 UTC by nkryuchkov

Closes #345.

In this PR, `internal/httpauth` requests a new nonce and retries HTTP request if a nonce validation error is returned.

2019-05-13 08:34 UTC, ayuryshev requested changes
I think it could be improved with introducing two configuration values:
- timeout between sequential `Client.Do`  requests for nonce
- recursion limit for `Client.Do` requests

2019-05-13 08:34 UTC, ayuryshev commented on internal/httpauth/client.go
> +		res, err = c.client.Do(req)
In "theory" recursive calls could continue now infinitely.
IMO it could be be improved with recursion call limit.
With `return nil,err` on overruns.

2019-05-13 08:34 UTC, ayuryshev commented on internal/httpauth/client.go
> +		time.Sleep(retryInterval)
`retryInterval` would be better if it was a settings value IMO

2019-05-13 09:55 UTC, ivcosla commented on internal/httpauth/client.go
> +		res, err = c.client.Do(req)
agree

2019-05-13 09:56 UTC, ivcosla commented on internal/httpauth/client.go
> +		time.Sleep(retryInterval)
About this I don't feel it's a parameter that the user is going to be concerned about, I feel it's fine as a constant in package.

2019-05-13 09:56 UTC, ivcosla approved these changes
Good job.

2019-05-13 20:02 UTC, nkryuchkov commented on internal/httpauth/client.go
> +		res, err = c.client.Do(req)
Thanks, I think it's a good idea. Added a commit with the implementation of max retries threshold as well as a test for it.

2019-05-13 20:28 UTC, evanlinjin commented on internal/httpauth/client.go
> +		time.Sleep(retryInterval)
Why do we need a retry parameter? It is not a network error.

2019-05-15 02:28 UTC, evanlinjin requested changes
Good work! Please review my comments.

2019-05-15 02:28 UTC, evanlinjin commented on internal/httpauth/client.go
> +	for retriesCount := 0; retriesCount < maxRetries; retriesCount++ {
As we are not dealing with a network error, I suggest the following changes:
1. One retry is plenty. If nonce is not synced, we only need to sync once afterwards.
2. We will not need a timeout or `retryInterval`.

2019-05-15 02:28 UTC, evanlinjin commented on internal/httpauth/client.go
> +	for retriesCount := 0; retriesCount < maxRetries; retriesCount++ {
Instead of a `for` loop, I would group lines `94-121` into a closure (excluding 110-112). And do `c.Nonce()` + `c.SetNonce()` + `call-closure-again` on error.

2019-05-15 02:28 UTC, evanlinjin commented on internal/httpauth/client.go
> +func (c *Client) isNonceValid(res *http.Response) (bool, error) {
1. Please leave a comment on this function.
2. We aren't using `c *Client`, please have it removed.

2019-05-15 02:28 UTC, evanlinjin commented on internal/httpauth/client_test.go
> +func TestBadNonce(t *testing.T) {
Please rename to `TestClient_BadNonce` and add a comment summarizing the test.

2019-05-15 02:28 UTC, evanlinjin commented on internal/httpauth/client_test.go
> +func TestTooManyRetries(t *testing.T) {
Please rename to `TestClient_TooManyRetries` and add a comment summarizing the test.

2019-05-16 08:33 UTC, nkryuchkov commented on internal/httpauth/client_test.go
> +func TestTooManyRetries(t *testing.T) {
Since we do not need to retry multiple times anymore, the test is removed.

2019-05-16 12:27 UTC, nkryuchkov commented
@evanlinjin The requested changes are made. Could you review the last changes, please?

2019-05-16 12:47 UTC, evanlinjin requested changes
Looks good. Just one more thing.

2019-05-16 12:47 UTC, evanlinjin commented on internal/httpauth/client.go
>  func (c *Client) getCurrentNonce() Nonce {
Operations to `c.nonce` should be atomic. Please use [`atomic.LoadUint64`](https://golang.org/pkg/sync/atomic/#LoadUint64). Also add a comment to line 48, that `c.nonce` is to be handled with the atomic package at all times.

2019-05-16 13:03 UTC, ayuryshev approved these changes

2019-05-16 13:14 UTC, nkryuchkov commented on internal/httpauth/client.go
>  func (c *Client) getCurrentNonce() Nonce {
Fixed

2019-05-16 13:16 UTC, evanlinjin approved these changes

2019-05-16 13:23 UTC, merged