[WIP] added retry on sequence error for update
skycoin/skywire-testnet pull request #351
Opened 2019-05-15 17:18 UTC by ivcosla

2019-05-16 19:18 UTC, ivcosla commented
The bug seems fixed, however we might want to make some changes to how to deal with retry.

2019-05-17 08:01 UTC, ivcosla commented
Closes #350

2019-05-20 07:27 UTC, jdknives commented
This is ready for review? @ivcosla

2019-05-20 07:30 UTC, ivcosla commented
yes

2019-05-20 12:02 UTC, nkryuchkov commented on pkg/messaging-discovery/client/client.go
> +		if err != nil {
I would check if `err == nil` here and `return nil` in this case. IMO this would make to code clearer and allow us to remove one level of indentation along with `continue` statement.

2019-05-20 13:15 UTC, Darkren commented
Agree with Nikita on stated above. Otherwise looks fine to me

2019-05-20 13:47 UTC, nkryuchkov commented on pkg/messaging-discovery/client/testing.go
> +		if err != nil {
Could you please invert the if statement and remove the `continue` statement below too?

2019-05-20 13:55 UTC, ayuryshev approved these changes

2019-05-20 13:57 UTC, nkryuchkov approved these changes

2019-05-21 10:45 UTC, evanlinjin requested changes
Looks good. Some requests.

2019-05-21 10:45 UTC, evanlinjin commented on pkg/messaging-discovery/client/client.go
> +		if err != nil {
Also consider moving `e.Sign` to the top of the `for` loop. This way, we can remove 124-127.

2019-05-21 10:47 UTC, evanlinjin commented on pkg/messaging-discovery/client/client.go
> +		if err == nil {
Also I would have `if err != nil` here and have error-handling code within that. This way it explicitly states; "This is error-handling code". But this is a matter of personal-taste and you can choose otherwise :P

2019-05-21 15:43 UTC, merged