Add column `mode-of-operation` in the `skywire-cli node ls-tp` output
skycoin/skywire-testnet pull request #362
Opened 2019-05-21 17:17 UTC by Darkren

Related to #335 

Had to add the `IsSetupTransport` to `mockRouter` and not really sure how this should be done properly, so it's a subject for discussion

2019-05-21 18:39 UTC, ayuryshev approved these changes
It would be great if example of output was included in PR text.
E.g.
```bash 
$ ./skywire-cli node ls-tp
# ... output here ...
```

Code changes itself looks good.

2019-05-21 18:39 UTC, ayuryshev commented on cmd/skywire-cli/commands/node/transports.go
> +	_, err := fmt.Fprintln(w, "type\tid\tlocal\tremote\tmode-of-operation")
I think "mode-of-operation" could be shortened to "mode".
And it would be great if example of output was included in PR text.

2019-05-21 19:35 UTC, Darkren commented on cmd/skywire-cli/commands/node/transports.go
> +	_, err := fmt.Fprintln(w, "type\tid\tlocal\tremote\tmode-of-operation")
Fixed that. Indeed, `mode-of-operation` couldn't be fit on my laptop screen @ayuryshev

2019-05-21 19:38 UTC, nkryuchkov approved these changes
Looks good to me

2019-05-22 04:50 UTC, evanlinjin requested changes
Looks good! However I think we can remove the `local` column. Sorry I didn't mention this earlier.

2019-05-22 05:29 UTC, nkryuchkov commented
Removed the column @evanlinjin

2019-05-22 11:14 UTC, jdknives commented
remove .bin @Darkren

2019-05-22 11:21 UTC, ivcosla approved these changes
As @jdknives said, remove routing.db and this is ready to merge.

2019-05-22 11:28 UTC, Darkren commented
Removed .bin @ivcosla @jdknives

2019-05-22 11:40 UTC, merged