[WIP] Feature: embedded profiling of skywire-node
skycoin/skywire-testnet pull request #399
Opened 2019-06-09 03:04 UTC by ayuryshev

# Feature: embedded profiling of skywire-node

## Major changes

### 1. Implemented ability to collect *.pprof files on exit of skywire-node

To create profiling data add flag `--pprof/-p` for skywire-node.

Possible values:
- cpu
- mem
- mutex
- block

pprof-files will be generated on exit in ./logs/[--tag]/[mode].pprof

To generate a report use `go tool pprof`

E.g. 

```bash
$ ./bin/skywire-node ./integration/generic/nodeA.json --tag NodeA --pprof
cpu
# Run tests
# then Ctrl-C
$ go tool pprof --pdf ~/bin/skywire-node ./logs/nodeA/cpu.pprof
```

### 2. Interactive profiling

Run skywire-node with `--pprof http --pport 6060`
(--pport has default value 6060 and could be ommitted when only one node
profiled)

E.g.
```bash 
$ skywire-node ./integration/generic/nodeA.json --tag NodeA --pprof http
$ go tool http://localhost:6060/debug/pprof/
```

Read: 

- https://golang.org/pkg/net/http/pprof/
- https://blog.golang.org/profiling-go-programs 
- https://godoc.org/github.com/pkg/profile

## Minor changes in Makefile

### 1. Environment variable $BUILD_OPTS with default value: "-race"

Motivation:

Need to switch on/off `-race` flag for various tests and various profiles.

Now it's possible:

```bash
$ export BUILD_OPTS=
$ make build  # or `make integration-build`
# note that binaries built without -race flag 
```

2. Environment variable $TEST_OPTS with default value: "-race -tags no_ci -cover -timeout=5m"

Motivation:

- `-timeout=5m` - is a good, safe timeout  for travis-ci 
- for developer environments it's more comfortable to use 60s (maximum
90s)

Now it's possible:

```bash 
$ export TEST_OPTS="-race -tags no_ci -timeout=60s"                                                                                                  5:41
$ make test
# note that timeout is not 5m now
```

# Why [WIP] 

Need to tidy code before.
So please don't write right now suggestions "move all pprof stuff into separate function"

2019-06-13 08:33 UTC, ivcosla commented on integration/InteractiveEnvironments.md
> +# Interactive test environments
Very uselful file. Good job!

2019-06-14 08:11 UTC, ayuryshev commented on integration/InteractiveEnvironments.md
> +# Interactive test environments
It's because this PR is based on https://github.com/skycoin/skywire/pull/393

2019-06-18 11:35 UTC, Darkren requested changes

2019-06-18 11:35 UTC, Darkren commented on cmd/skywire-node/commands/root.go
> +	var option func(*profile.Profile)
Wouldn't it be better if we could write several profiles at once? For example, `cpu` and `mem`. There are a situations when sometimes it hangs, sometimes it doesn't, it is not that comfortable to get profiles from several runs, they may not show the whole picture

2019-06-25 09:20 UTC, merged