Implementation of dmsg.
skycoin/skywire-testnet pull request #402
Opened 2019-06-10 12:12 UTC by evanlinjin

This is a renaming of #382

2019-06-19 07:36 UTC, ivcosla requested changes
Nice work overall, just a few things to check.

2019-06-19 07:36 UTC, ivcosla commented on pkg/dmsg/README.md
> +- A `dmsg.Client` manages the assignment of positive transport IDs between itself and each connected `dmsg.Server`. The set of transport IDs will be unique between itself and each `dmsg.Server`.
Here we talk about positive/negative transports IDs, while below we do so about even/odd tranport IDs

2019-06-19 07:36 UTC, ivcosla commented on pkg/dmsg/transport.go
> +type Transport struct {
Transport has a lot of fields and what they should be used for can be therefore confusing, I would suggest to cluster the ones that are related together in new and small objects if possible. 

However take this as a comment, I would leave it for later since is not prioritary, but definitely do it in the future.

2019-06-19 07:36 UTC, ivcosla commented on pkg/dmsg/transport.go
> +func (tp *Transport) Serve() {
This function is also something to simplify in the future

2019-06-19 07:36 UTC, ivcosla commented on pkg/dmsg/client_test.go
> +		go func() {
A lot of patterns are repeated in these two functions, like the conn.Serve go routines, conn initialization, etc. I would suggest to extract some of them as functions to improve readability.

For example:

```go
conn1, conn2, conn3, conn4 := setupTransports()
```

2019-06-19 07:43 UTC, evanlinjin commented on pkg/dmsg/README.md
> +- A `dmsg.Client` manages the assignment of positive transport IDs between itself and each connected `dmsg.Server`. The set of transport IDs will be unique between itself and each `dmsg.Server`.
Sorted.

2019-06-19 08:39 UTC, evanlinjin commented on pkg/dmsg/transport.go
> +func (tp *Transport) Serve() {
@ivcosla I would have to disagree on this one. The logic is simple, we are handling incoming frames, and handling them based on it's type. I would say that maybe some comments on the logic would make things easier though.

2019-06-19 08:40 UTC, ivcosla commented on pkg/dmsg/transport.go
> +func (tp *Transport) Serve() {
I agree is not difficult, just very long, well, up to you.

2019-06-19 09:18 UTC, evanlinjin commented on pkg/dmsg/transport.go
> +type Transport struct {
@ivcosla I've added comments to the fields as a compromise. As the code-base for `dmsg.Transport` is relatively small, I feel that splitting it up into multiple structures will not make the code easier to read.

2019-06-19 09:40 UTC, ivcosla commented on pkg/dmsg/transport.go
> +type Transport struct {
That might be enough, good job.

2019-06-20 12:42 UTC, ayuryshev reviewed
1. Code is much more readable than in `messaging` and package itself much more simple
2. There are still some places that not so clear - explanations or changes needed
3. Overall - good work! It's a progress over messaging

2019-06-20 12:42 UTC, ayuryshev commented on Makefile
> +	${OPTS} go build -race -o ./messaging-server ./cmd/messaging-server
What is the reason to move messaging-server from skywire-services?
Is it temporary measure?

2019-06-20 12:42 UTC, ayuryshev commented on internal/ioutil/ack_waiter_test.go
> +package ioutil
Consider make this tests blackbox: only public API is tested here

```golang
package ioutil_test

import (
	"context"
	"sync"
	"testing"

	"github.com/skycoin/skywire/internal/ioutil"
)
func TestUint16AckWaiter_Wait(t *testing.T) {

	// Ensure that no race conditions occurs when
	// each concurrent call to 'Uint16AckWaiter.Wait()' is met with
	// multiple concurrent calls to 'Uint16AckWaiter.Done()' with the same seq.
	t.Run("ensure_no_race_conditions", func(*testing.T) {
		w := new(ioutil.Uint16AckWaiter)
		defer w.StopAll()

		seqChan := make(chan ioutil.Uint16Seq)
		defer close(seqChan)

		wg := new(sync.WaitGroup)

		for i := 0; i < 64; i++ {
			wg.Add(1)
			go func() {
				defer wg.Done()
				_ = w.Wait(context.TODO(), func(seq ioutil.Uint16Seq) error { //nolint:errcheck,unparam
					seqChan <- seq
					return nil
				})
			}()

			seq := <-seqChan
			for j := 0; j <= i; j++ {
				wg.Add(1)
				go func() {
					defer wg.Done()
					w.Done(seq)
				}()
			}
		}

		wg.Wait()
	})
}

```

2019-06-20 12:42 UTC, ayuryshev commented on internal/ioutil/atomic_bool.go
> +type AtomicBool struct {
I can't find usage of this type.
I consider to drop it.

2019-06-20 12:42 UTC, ayuryshev commented on internal/ioutil/buf_read.go
> +func BufRead(buf *bytes.Buffer, data, p []byte) (int, error) {
I see only one usage of this function.

Does it deserves a separate file?

2019-06-20 12:42 UTC, ayuryshev commented on internal/noise/net.go
> +		if err := rw.Handshake(time.Second * 10); err != nil {
`time.Second * 10` is meant to be configurable?

2019-06-20 12:42 UTC, ayuryshev commented on internal/noise/noise.go
> +var log = logging.MustGetLogger("noise")
`var log` is used inside "github.com/skycoin/skycoin/src/util/logging" for `MasterLogger`.

Althought it's syntactically correct I would consider to use `logger` or `noiseLogger` here.

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/README.md
> +- **entity -** A service of `dmsg` (typically being part of an executable running on a machine).
Explanation starts with "A service"
So why not use "service" instead of vague "entity"

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/README.md
> +- **entity type -** The type of entity. `dmsg` has three entity types; `dmsg.Server`, `dmsg.Client`, `dmsg.Discovery`.
**service type** ? 
"has three service types:" ?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/README.md
> +- **entry -** A data structure that describes an entity and is stored in `dmsg.Discovery` for entities to access.
It clashes with Entry-types from transport.
And here meaning "describes dmsg service" - right?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/README.md
> +- **transport ID -** A uint16 value that identifies a transport.
Is it implementation detail or part of public API?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/README.md
> +- **connection -** The direct line of duplex communication between a `dmsg.Server` and `dmsg.Client`.
I never saw "line of communication" used for networks.
Googled - it looks like military/business terminology.

Why not just change to "network connection"?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/README.md
> +- `dmsg.Server` proxies frames between clients.
"proxies frames" - "frames" here "packets"?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/README.md
> +| `0xa` | `FWD` | uint16 sequence + transport payload | >2 |
Why `0xa` here?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/README.md
> +Hence, a transport in it's entirety, is represented by 2 transport IDs.
`transport.Transport` already has public `Edges()` which are 2 IDs.
And `dmgs.Transport` too.

Those `uint16` IDs:
- has only internal meaning for dmsg
- part of public API
?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/README.md
> +- The destination of the transport, after receiving the `FWD` frame, responds with an `ACK` frame with the same sequence as the payload.
ACK frame does not contains some checksum of FWD payload?
It's always successful?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/client.go
> +	tps [math.MaxUint16 + 1]*Transport
1. `tps` has strong association with "transactions-per-second"
I would consider to rename it.

2. `tps [math.MaxUint16 + 1]*Transport` - what is the purpose of creating array of 65536 elements beforehand?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/client.go
> +func (c *ClientConn) getNextInitID(ctx context.Context) (uint16, error) {
Why not atomic AddUInt here?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/client.go
> +	c.nextInitID = nextInitID
Again: I would consider atomics here

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/client.go
> +func (c *ClientConn) handleRequestFrame(accept chan<- *Transport, id uint16, p []byte) (cipher.PubKey, error) {
`p []byte` here - payload?
I would consider to add several symbols here.

`data`?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/client.go
> +func (c *ClientConn) Close() error {
Is it safe to repeat `c.Close()` multiple times?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/client.go
> +	if !closed {
So the second c.Close() will return ErrClientClosed?
What is the meaning of this error here?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/client.go
> +func (c *Client) SetLogger(log *logging.Logger) {
Why not assign logger only once - in NewClient?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/client.go
> +func (c *Client) updateDiscEntry(ctx context.Context) error {
This method is thread-unsafe by design?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/client.go
> +func (c *Client) setConn(ctx context.Context, l *ClientConn) {
`l *ClientConn` - why `l` ?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/client.go
> +	go func() {
This gouroutine deserves to be named IMO.

```golang
func (c *Client) serve(ctx context.Context, conn *ClientConn, srvPK cipher.PubKey) {
	err := conn.Serve(ctx, c.accept)
	conn.log.WithError(err).WithField("remoteServer", srvPK).Warn("connected with server closed")
	c.delConn(ctx, srvPK)

	// reconnect logic.
retryServerConnect:
	select {
	case <-c.done:
	case <-ctx.Done():
	case <-time.After(time.Second * 3):
		conn.log.WithField("remoteServer", srvPK).Warn("Reconnecting")
		if _, err := c.findOrConnectToServer(ctx, srvPK); err != nil {
			conn.log.WithError(err).WithField("remoteServer", srvPK).Warn("ReconnectionFailed")
			goto retryServerConnect
		}
		conn.log.WithField("remoteServer", srvPK).Warn("ReconnectionSucceeded")
	}
}
```
?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/client_test.go
> +		conn2.setNextInitID(randID(false))
Why this needed?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/client_test.go
> +		go func() {
Why not use just one `errCh` here?
And 
```golang
		for _, conn := range []*ClientConn{conn1, conn2, conn3, conn4} {
			errCh1 <- conn.Close()
		}
```

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/client_test.go
> +type invertedIDConn struct {
What is the meaning of this type?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/client_test.go
> +	newFrame := MakeFrame(frame.Type(), frame.TpID()^1, frame.Pay())
InvertedIDConn will be even for odd and otherwise?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/frame.go
> +	hsTimeout     = time.Second * 10
`time.Second*10` - configuration value?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/frame.go
> +	acceptChSize  = 20
Configuration value?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/frame.go
> +func isInitiatorID(tpID uint16) bool { return tpID%2 == 0 }
Is it needed to give name for even-odd checks?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/frame.go
> +		if initiator && id%2 == 0 || !initiator && id%2 != 0 {
random value here is not required to be crypto-random, right?

Why not rand.IntN(math.MaxUInt16) ?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/frame.go
> +func incrementServeCount() int64 { return atomic.AddInt64(&serveCount, 1) }
Are those functions needed?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/frame.go
> +	FwdType     = FrameType(0xa)
Why `0xa`?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/frame.go
> +func isWriteError(err error) bool {
Why this function needed?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/frame.go
> +func writeFrame(w io.Writer, f Frame) error {
`writeFrame` here and below has meaning `sendPacket`?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/frame_test.go
> +func Test_isInitiatorID(t *testing.T) {
Is it test for even/odd?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/frame_test.go
> +func Test_randID(t *testing.T) {
and this too?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/frame_test.go
> +func TestFrameType_String(t *testing.T) {
I would consider to write it:

```golang
func ExampleFrameType_String() {
	fmt.Printf("%v\n", RequestType)
	fmt.Printf("%v\n", AcceptType)
	fmt.Printf("%v\n", CloseType)
	fmt.Printf("%v\n", FwdType)
	fmt.Printf("%v\n", AckType)
	fmt.Printf("%v\n", FrameType(0x0))
	fmt.Printf("%v\n", FrameType(0xFF))
	// Output: REQUEST
	// ACCEPT
	// CLOSE
	// FWD
	// ACK
	//
	// UNKNOWN:255
}
```

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/frame_test.go
> +func TestFrame_Type(t *testing.T) {
Second test for converting FrameType?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/server.go
> +	l  *ServerConn
`l *ServerConn`: 
- `l` is not recommended as variable name because of similarity with `1`
- why connection named `l`?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/server.go
> +	nextConns  [math.MaxUint16 + 1]*NextConn
Please explain here.

A) There is another array of 65536 *NextConn created from start - what is the motivation for this?

B) Does it means ServerConn is recursive structure?
Something similar with:

```golang
type ServerConnTree struct {
	log *logging.Logger
	net.Conn
	remoteClient cipher.PubKey

	nextConns [65536]*ServerConnTree
}
```
Why?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/server.go
> +	c.nextRespID = id + 2
Why not atomic AddUint?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/server.go
> +			err = errors.New("listener has not started")
Please explain this error message

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/server.go
> +	s.conns = make(map[cipher.PubKey]*ServerConn)
Why it's needed to recreate s.conns on Close?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/server_test.go
> +				log:          logging.MustGetLogger("ServerConn"),
I would consider add 
```golang
func TestingMain(t *testing.T){
}
```
and init repetetive things in it

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/server_test.go
> +func TestServer_Serve(t *testing.T) {
This function is ~400 LOCs
I would consider to split it

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/transport.go
> +func (tp *Transport) Edges() [2]cipher.PubKey {
I would consider to Sort Edges only in NewTransport
And then make them immutable

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/transport.go
> +func (tp *Transport) Inject(f Frame) error {
What Inject means here? Send?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/transport.go
> +func (tp *Transport) Close() error {
Is it safe to call Close() multiple times?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/transport.go
> +				select {
What is the meaning of `case <- tp.done:` here?

I see the only possible sense is to send `tp.bufCh <- struct{}{}:` asynchronously.

I suppose it will be equivalent to:
```golang
go func(tp *Transport){ tp.bufCh <- struct{}{} }(tp)
```

2019-06-20 12:42 UTC, ayuryshev commented on pkg/dmsg/transport.go
> +	<-tp.serving
Does it needed to guard transport with `<-tp.serving`?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/node/node.go
> +	messenger *dmsg.Client
Why not `transport.Factory` here?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/transport/handshake_test.go
> +//func Example_validateEntry() {
For removal or revival?

2019-06-20 12:42 UTC, ayuryshev commented on pkg/transport/transport.go
> +func MakeTransportID(keyA, keyB cipher.PubKey, tpType string, public bool) uuid.UUID {
I thought about moving those funcs from `manager.go`
And I thought about moving them near transport.Entry types.

2019-06-20 12:58 UTC, evanlinjin commented on pkg/dmsg/client.go
> +func (c *ClientConn) handleRequestFrame(accept chan<- *Transport, id uint16, p []byte) (cipher.PubKey, error) {
https://talks.golang.org/2014/names.slide#8

2019-06-20 12:59 UTC, evanlinjin commented on internal/noise/noise.go
> +var log = logging.MustGetLogger("noise")
I personally don't see this as a problem. Might need some input from others.

2019-06-20 13:01 UTC, evanlinjin commented on internal/ioutil/buf_read.go
> +func BufRead(buf *bytes.Buffer, data, p []byte) (int, error) {
@ayuryshev I think we should leave it as it. We may use the same logic again for later implementations of `io.Reader`

2019-06-20 13:13 UTC, evanlinjin commented on Makefile
> +	${OPTS} go build -race -o ./messaging-server ./cmd/messaging-server
We will eventually move all `dmsg`-associated parts to it's own repo. It will be a good call to move this here first.

2019-06-20 13:13 UTC, evanlinjin commented on internal/ioutil/atomic_bool.go
> +type AtomicBool struct {
I think we can leave it for now. We may use it later.

2019-06-20 13:13 UTC, evanlinjin commented on pkg/dmsg/README.md
> +| `0xa` | `FWD` | uint16 sequence + transport payload | >2 |
No particular reason. I just wanted to separate FWD and ACK frame types from the rest.

2019-06-20 13:15 UTC, evanlinjin commented on pkg/dmsg/client.go
> +	tps [math.MaxUint16 + 1]*Transport
1. I think in this context it means "transports".
2. We either use maps for this. This is more performant (but uses more memory). This needs to be performant, as we call from it every time a frame is received.

2019-06-20 13:16 UTC, evanlinjin commented on pkg/dmsg/client.go
> +func (c *ClientConn) getNextInitID(ctx context.Context) (uint16, error) {
Because operations to the associated `uint16` value needs to be atomic in combination with other operations. Hence, `atomic` will not be a viable solution.

2019-06-20 13:16 UTC, evanlinjin commented on pkg/dmsg/client.go
> +	c.nextInitID = nextInitID
Not a viable solution.

2019-06-20 13:18 UTC, evanlinjin commented on pkg/dmsg/client.go
> +func (c *ClientConn) Close() error {
Yes, as we use `sync.Once`

2019-06-20 13:20 UTC, evanlinjin commented on pkg/dmsg/client.go
> +	if !closed {
Yes. The meaning of this error is that the connection is already closed. I was following the behavior of how `.Close` would function in `net` interfaces. But it is not needed.

2019-06-20 13:21 UTC, evanlinjin commented on pkg/dmsg/client.go
> +func (c *Client) SetLogger(log *logging.Logger) {
It's a matter of taste. I like this better.

2019-06-20 13:21 UTC, evanlinjin commented on pkg/dmsg/client.go
> +func (c *Client) updateDiscEntry(ctx context.Context) error {
Correct.

2019-06-20 13:21 UTC, evanlinjin commented on pkg/dmsg/client.go
> +func (c *Client) setConn(ctx context.Context, l *ClientConn) {
`Conn` was called `Link`before.

2019-06-20 13:28 UTC, evanlinjin commented on pkg/dmsg/client.go
> +	go func() {
@ayuryshev generally I would agree. But I think the readability is fine here.

2019-06-20 13:34 UTC, evanlinjin commented on pkg/dmsg/client_test.go
> +		go func() {
I think it is fine as is. As long as the test is easy to read and does what is should, I don't think it is worth changing.

2019-06-20 13:35 UTC, evanlinjin commented on pkg/dmsg/client_test.go
> +type invertedIDConn struct {
It's so that we can directly get two `ClientConn`s communicating with one another.

2019-06-20 13:35 UTC, evanlinjin commented on pkg/dmsg/client_test.go
> +type invertedIDConn struct {
I'll write a comment.

2019-06-20 13:36 UTC, ayuryshev commented on internal/noise/noise.go
> +var log = logging.MustGetLogger("noise")
It's not a problem
But:
- pkg/log - from stdlib
- var log in util/logging
- and here `log` again 

All three places it has different meaning: package, MasterLogger, PackageLogger

2019-06-20 13:37 UTC, evanlinjin commented on pkg/dmsg/client_test.go
> +	newFrame := MakeFrame(frame.Type(), frame.TpID()^1, frame.Pay())
Yes. Comment added.

2019-06-20 13:43 UTC, ayuryshev commented on internal/ioutil/atomic_bool.go
> +type AtomicBool struct {
In this case I would consider to change signature to:
```golang
func (b *AtomicBool) Set(v bool) 
```
detection "if the value is changed" - is simpler to write with CompareAndSwap when needed

2019-06-20 13:51 UTC, ayuryshev commented on internal/ioutil/buf_read.go
> +func BufRead(buf *bytes.Buffer, data, p []byte) (int, error) {
I don't understand how it helps to write `Reader`s

2019-06-20 14:06 UTC, evanlinjin commented on pkg/dmsg/frame.go
> +func isInitiatorID(tpID uint16) bool { return tpID%2 == 0 }
It makes the code more readable.

2019-06-20 14:06 UTC, evanlinjin commented on pkg/dmsg/frame.go
> +		if initiator && id%2 == 0 || !initiator && id%2 != 0 {
I think it is fine.

2019-06-20 14:07 UTC, evanlinjin commented on pkg/dmsg/frame.go
> +func incrementServeCount() int64 { return atomic.AddInt64(&serveCount, 1) }
Yes. Those are used.

2019-06-20 14:07 UTC, evanlinjin commented on pkg/dmsg/frame.go
> +func isWriteError(err error) bool {
The name of the function gives it away.

2019-06-20 14:09 UTC, evanlinjin commented on pkg/dmsg/frame.go
> +func writeFrame(w io.Writer, f Frame) error {
We are calling the data units of `dmsg` frames.

2019-06-20 14:17 UTC, evanlinjin commented on pkg/dmsg/frame_test.go
> +func TestFrameType_String(t *testing.T) {
I wouldn't use an example for it, but I think the use of `cases` is a little excessive.

2019-06-20 14:18 UTC, evanlinjin commented on pkg/dmsg/frame_test.go
> +func TestFrame_Type(t *testing.T) {
Yes, I do agree that the test for frames is a little excessive.

2019-06-20 14:27 UTC, evanlinjin commented on pkg/dmsg/server.go
> +	nextConns  [math.MaxUint16 + 1]*NextConn
A) Performance > Memory usage.
B) I wouldn't call it a tree structure. The Server stores connections with Clients, a frame sent from one client needs to get forwarded to another client.

2019-06-20 14:29 UTC, evanlinjin commented on pkg/dmsg/server.go
> +	c.nextRespID = id + 2
The `AddUint` and other operations together (in a group) needs to be handled atomically. So not just the `uint16` value itself.

2019-06-20 14:33 UTC, evanlinjin commented on internal/noise/noise.go
> +var log = logging.MustGetLogger("noise")
I think because of the context of where we are using it, it is fine.

2019-06-20 14:34 UTC, evanlinjin commented on pkg/dmsg/server.go
> +			err = errors.New("listener has not started")
Legacy code. removed.

2019-06-20 14:35 UTC, evanlinjin commented on pkg/dmsg/server.go
> +	s.conns = make(map[cipher.PubKey]*ServerConn)
@ayuryshev just in case some goroutines try to read/write to it after close is called.

2019-06-20 14:37 UTC, evanlinjin commented on pkg/dmsg/server_test.go
> +func TestServer_Serve(t *testing.T) {
Consider each sub-test as it's own function. Yes some sub-tests needs simplifications.

2019-06-20 14:40 UTC, evanlinjin commented on pkg/dmsg/transport.go
> +func (tp *Transport) Edges() [2]cipher.PubKey {
In the future, `transport.Transport` interface will have `Local() cipher.Pubkey` and `Remote() cipher.Pubkey` definitions. The `Edges()` addition turned out to be a hassle in certain cases (because we need additional calls to determine which is the remote/local edge). I think we can leave it for now.

2019-06-20 14:43 UTC, evanlinjin commented on pkg/dmsg/transport.go
> +func (tp *Transport) Inject(f Frame) error {
add, introduce, insert, instill, etc.

2019-06-20 14:43 UTC, evanlinjin commented on pkg/dmsg/transport.go
> +func (tp *Transport) Inject(f Frame) error {
I'm happy with this naming convention. Also open for other opinions.

2019-06-20 14:44 UTC, evanlinjin commented on pkg/dmsg/transport.go
> +func (tp *Transport) Close() error {
Yes

2019-06-20 14:46 UTC, evanlinjin commented on pkg/dmsg/transport.go
> +				select {
> What is the meaning of `case <- tp.done:` here?
Return on close.

> I see the only possible sense is to send `tp.bufCh <- struct{}{}:` asynchronously.
The chan is buffered with size of 1.

> I suppose it will be equivalent to: ...
No, this introduces unnecessary go routines.

2019-06-20 14:47 UTC, evanlinjin commented on pkg/node/node.go
> +	messenger *dmsg.Client
@ayuryshev I think we can leave it for now. It's for calling the `InitiateServerConnections` function.

2019-06-20 14:47 UTC, evanlinjin commented on pkg/transport/handshake_test.go
> +//func Example_validateEntry() {
Revival

2019-06-20 14:58 UTC, evanlinjin commented on pkg/dmsg/README.md
> +- **entity -** A service of `dmsg` (typically being part of an executable running on a machine).
I think entity is fine. We talk about `skywire services` so I didn't want to reuse "services". "Service" also suggests running as an executable on a machine, but it is not necessarily the case here.

2019-06-20 14:58 UTC, evanlinjin commented on pkg/dmsg/README.md
> +- **entity type -** The type of entity. `dmsg` has three entity types; `dmsg.Server`, `dmsg.Client`, `dmsg.Discovery`.
Yes.

2019-06-20 14:59 UTC, evanlinjin commented on pkg/dmsg/README.md
> +- **entry -** A data structure that describes an entity and is stored in `dmsg.Discovery` for entities to access.
`dmsg` Entity. They are both discoveries (dmsg discovery, transport discovery), discoveries have entries.

2019-06-20 15:01 UTC, evanlinjin commented on pkg/dmsg/README.md
> +- **transport ID -** A uint16 value that identifies a transport.
The point here is that it is represented by a number. We mention later on about using the even/odd property of the ID to determine role.

2019-06-20 15:06 UTC, evanlinjin commented on pkg/dmsg/README.md
> +- **connection -** The direct line of duplex communication between a `dmsg.Server` and `dmsg.Client`.
"line of communication" and "lines of communication" is common English. It's not military-specific.

2019-06-20 15:08 UTC, ayuryshev commented on pkg/dmsg/README.md
> +- **connection -** The direct line of duplex communication between a `dmsg.Server` and `dmsg.Client`.
It's not network terminology either

2019-06-20 15:09 UTC, evanlinjin commented on pkg/dmsg/README.md
> +- `dmsg.Server` proxies frames between clients.
We are using `frame` as the term for data units within `dmsg`.

2019-06-20 15:11 UTC, evanlinjin commented on pkg/dmsg/README.md
> +Hence, a transport in it's entirety, is represented by 2 transport IDs.
We have the definition: `**transport ID -** A uint16 value that identifies a transport.`

You can say that it has only internal meaning for dmsg, but if we want to ignore all internal meanings, then the definition for `transport.Transport` interface will be sufficient enough for `dmsg` specs.

2019-06-20 15:13 UTC, evanlinjin commented on pkg/dmsg/README.md
> +- The destination of the transport, after receiving the `FWD` frame, responds with an `ACK` frame with the same sequence as the payload.
We state in `TODO`: ``ACK` frames should include the first 4 bytes of the rolling hash of incoming payloads, enforcing reliability of data. Transports should therefore keep track of incoming/outgoing rolling hashes.`

and yes.

2019-06-20 15:13 UTC, ayuryshev commented on pkg/dmsg/client.go
> +	tps [math.MaxUint16 + 1]*Transport
I would consider map here - exactly as in comment.
Performance here will be all eaten with network io and concurrency.

2019-06-20 15:15 UTC, evanlinjin commented on pkg/dmsg/transport.go
> +	<-tp.serving
Yes. We need to wait until the transport handshake completes.

2019-06-20 15:20 UTC, ayuryshev commented on pkg/dmsg/transport.go
> +func (tp *Transport) Inject(f Frame) error {
`Inject` - has strong connotation with packet injection.
It seems clear that it was not intentional.
`Transport.SendFrame`? `Transport.SendPacket`?

I prefer `Packets`: `Frames` usually for L2 and we are not doing L2 now.

2019-06-20 15:24 UTC, ayuryshev commented on pkg/dmsg/transport.go
> +				select {
There is no return on `case <-tp.done:`
And golang guarantee randomness of `select-case` branches.
So this construction will work completely random after `close(tp.done)`

Correct if I'm wrong here.

2019-06-20 15:29 UTC, ayuryshev commented on pkg/node/node.go
> +	messenger *dmsg.Client
It's not a problem at all:

```golang
func (node *Node) Start() error {
	ctx := context.Background()
	switch msgr := node.messenger.(type) {
	case *dmsg.Client:
		err := msgr.InitiateServerConnections(ctx, node.config.Messaging.ServerCount)
		if err != nil {
			return fmt.Errorf("%s: %s", dmsg.Type, err)
		}
		node.logger.Info("Connected to dmsg servers")
	case *messaging.MsgFactory:
		err := msgr.ConnectToInitialServers(ctx, node.config.Messaging.ServerCount)
		if err != nil {
			return fmt.Errorf("ConnectToInitialServers: %s", err)
		}
		node.logger.Info("Connected to messaging servers")
	}
```

2019-06-20 15:30 UTC, ayuryshev commented on pkg/transport/handshake_test.go
> +//func Example_validateEntry() {
OK

2019-06-20 15:43 UTC, evanlinjin commented on pkg/dmsg/transport.go
> +				select {
There is a possibility that the `tp.done` is going to be selected, but I do agree that it's not needed as we have the `default:` case.

Note that the `default` case is always selected last.

2019-06-20 15:46 UTC, evanlinjin commented on pkg/node/node.go
> +	messenger *dmsg.Client
@ayuryshev ideally that function is to be called outside of `Node`. But it's not. The solution you have provided is elegant, but it's not the optimal way.

I would rather stick with what's in the PR before we change to call `Initiate...` outside of `Node`.

2019-06-20 15:47 UTC, ayuryshev commented on pkg/dmsg/README.md
> +- **transport ID -** A uint16 value that identifies a transport.
I mean: details of even/odd, positive/negative, uint16/uint32 - could be absolutely insignificant if it's only dmgs implementation details.

We don't even need to document this if it's not public API

2019-06-20 15:47 UTC, ayuryshev commented on pkg/dmsg/README.md
> +- `dmsg.Server` proxies frames between clients.
So it's packets of data?

2019-06-20 15:49 UTC, evanlinjin commented on pkg/dmsg/README.md
> +- `dmsg.Server` proxies frames between clients.
The term we are using for the data unit within `dmsg` is `frame`. `packet` is for `Router`.

2019-06-20 15:50 UTC, evanlinjin commented on pkg/dmsg/README.md
> +- **transport ID -** A uint16 value that identifies a transport.
I think these provided details allow the codebase to be more readable. I will leave it as is.

2019-06-20 15:58 UTC, evanlinjin commented on pkg/dmsg/client.go
> +	tps [math.MaxUint16 + 1]*Transport
For sake of convenience, I will create a separate issue for this.

2019-06-20 16:03 UTC, ayuryshev commented on pkg/dmsg/client.go
> +func (c *ClientConn) getNextInitID(ctx context.Context) (uint16, error) {
Please explain.
What's needed from nextInitID?

`atomic.AddUint32` for increment
and
`atomic.LoadUint32` for get value

What else is needed?

2019-06-20 16:06 UTC, ayuryshev commented on pkg/dmsg/client.go
> +func (c *ClientConn) handleRequestFrame(accept chan<- *Transport, id uint16, p []byte) (cipher.PubKey, error) {
It's a good talk
And `b []byte` - indeed is traditional but `p []byte` - not.
I would consider to add some symbols here:
- `data`
- `frameData`
- `payload`
- `packedData`

Looks OK.

2019-06-20 16:09 UTC, evanlinjin commented on pkg/dmsg/client.go
> +func (c *ClientConn) getNextInitID(ctx context.Context) (uint16, error) {
The increment_next_id and get_next_id operations (together) need to be atomic. Otherwise we may run into the possibility of trying to allocate the same transport id in two different transports.

2019-06-20 16:12 UTC, ayuryshev commented on pkg/dmsg/client.go
> +func (c *Client) SetLogger(log *logging.Logger) {
Mutability is not a matter of taste. 
Each mutable member requires attention.
I could not imagine situation when it's needed to change Logger during Client lifetime.

I would consider to:
- init logger once
- remove SetLogger

2019-06-20 16:13 UTC, ayuryshev commented on pkg/dmsg/client.go
> +func (c *Client) setConn(ctx context.Context, l *ClientConn) {
Thanks for explanation

2019-06-20 16:16 UTC, ayuryshev commented on pkg/dmsg/client.go
> +	go func() {
It's not about readability but semantics. 
We had something similar in `transport.Manager` when critical code was unnamed.
IMO this code is equally significant - it deserves to at least be named.

2019-06-20 16:50 UTC, evanlinjin commented on pkg/dmsg/client.go
> +func (c *Client) SetLogger(log *logging.Logger) {
For note in the future: "I think it's better if ... because ..." would be a better tone of voice than "why ...?".

You have a point. I'll change this.

2019-06-20 17:01 UTC, ayuryshev commented on pkg/dmsg/client_test.go
> +		go func() {
This test is easy to beatify with simple deduplication.
Look: https://github.com/skycoin/skywire/blob/35e3bcb7c21b5b701823b3be57cfe6db4ead3c2d/pkg/dmsg/client_test.go#L209

I did not finished but idea must be clear:

```golang
		errCh := closeClosers(
			tr1, tr2, conn1, conn2, conn3, conn4,
		)

		assertNoError(t, errCh)

		assertFalse(t,
			isDoneChannelOpen(conn1.done),
			isDoneChannelOpen(conn3.done),
			isDoneChannelOpen(tr1.done),
			isReadChannelOpen(tr1.inCh),
			isDoneChannelOpen(tr2.done),
			isReadChannelOpen(tr2.inCh),
		)
```

2019-06-20 17:18 UTC, ayuryshev commented on pkg/dmsg/frame.go
> +		if initiator && id%2 == 0 || !initiator && id%2 != 0 {
I tend to disagree.
Simple task is solved in a complex way. 

Look:

```golang
func randID(initiator bool) uint16 {
	id := rand.Intn(tpBufCap)
	if id%2 == 0 && initiator {
		return uint16(id)
	}
	return uint16(id + 1)
}
```

2019-06-20 17:21 UTC, ayuryshev commented on pkg/dmsg/frame.go
> +func incrementServeCount() int64 { return atomic.AddInt64(&serveCount, 1) }
I  mean: why envelop just one call atomic.AddInt64 into function?
It's simple enough and absolutely readable

2019-06-20 17:24 UTC, ayuryshev commented on pkg/dmsg/frame_test.go
> +func TestFrameType_String(t *testing.T) {
`Example` is perfectly fits here: it's a test for `String()` representation.

2019-06-20 17:30 UTC, ayuryshev commented on pkg/dmsg/server.go
> +	nextConns  [math.MaxUint16 + 1]*NextConn
Look:

```golang
type NextConn struct {
	l  *ServerConn
	id uint16
}

type ServerConn struct {
	nextConns  [math.MaxUint16 + 1]*NextConn
}
```
Those types are mutually recursive.

And I don't see `Client`s here - there are only `ServerConn`s here.
What is the motivation by this?

2019-06-20 17:30 UTC, ayuryshev commented on pkg/dmsg/server.go
> +			err = errors.New("listener has not started")
OK

2019-06-20 17:35 UTC, evanlinjin commented on pkg/dmsg/server.go
> +	nextConns  [math.MaxUint16 + 1]*NextConn
@ayuryshev 
Yes, you can say that it is a recursive structure, however it is still not a tree.

> And I don't see Clients here - there are only ServerConns here.
> What is the motivation by this?

Why do we need to have `Client` here? Maybe I've misunderstood the question?

2019-06-20 17:43 UTC, ayuryshev commented on pkg/dmsg/transport.go
> -// Inject injects a frame from 'ClientConn' to transport.
My comment is not for this line but for line 98:
```golang
	tp.serve() // just in case.
	tp.ackWaiter.StopAll()
	return closed
}
```
(for reasons unknown for me github prohibits writing comment  directly)

I suppose that "just in case" - could be a subtle error.

2019-06-20 17:49 UTC, evanlinjin commented on pkg/dmsg/transport.go
> -// Inject injects a frame from 'ClientConn' to transport.
@ayuryshev what kind of subtle error are you suggesting?
- The actions within `tp.serve()` are protected with `sync.Once`.
- We need to call `tp.serve()` to unblock Read/Write (in case `tp.Serve` is not called).

2019-06-20 18:14 UTC, evanlinjin commented on pkg/dmsg/frame_test.go
> +func TestFrameType_String(t *testing.T) {
https://github.com/skycoin/skywire/issues/420

2019-06-20 18:14 UTC, evanlinjin commented on pkg/dmsg/server_test.go
> +				log:          logging.MustGetLogger("ServerConn"),
https://github.com/skycoin/skywire/issues/420

2019-06-20 18:14 UTC, evanlinjin commented on pkg/dmsg/server_test.go
> +func TestServer_Serve(t *testing.T) {
https://github.com/skycoin/skywire/issues/420

2019-06-20 18:15 UTC, evanlinjin commented on pkg/dmsg/frame_test.go
> +func TestFrame_Type(t *testing.T) {
https://github.com/skycoin/skywire/issues/420

2019-06-20 18:18 UTC, nkryuchkov commented on pkg/dmsg/client.go
> +	tps [math.MaxUint16 + 1]*Transport
What do you think of implementing a benchmark to compare array and map in this case?

2019-06-20 18:23 UTC, evanlinjin commented on pkg/dmsg/client.go
> +	tps [math.MaxUint16 + 1]*Transport
@nkryuchkov good idea, however this would be rather a time-consuming task because we need to consider multiple scenarios. I've created a ticket: https://github.com/skycoin/skywire/issues/419

Let's continue the discussion there!

2019-06-20 18:29 UTC, nkryuchkov commented on pkg/dmsg/frame.go
> +func incrementServeCount() int64 { return atomic.AddInt64(&serveCount, 1) }
@ayuryshev it's easier to read and abstracts the way how the value should be changed

2019-06-20 18:32 UTC, nkryuchkov commented on pkg/dmsg/frame_test.go
> +func Test_isInitiatorID(t *testing.T) {
@ayuryshev it tests that checking if an ID is initiator works correctly

2019-06-20 18:33 UTC, nkryuchkov commented on pkg/dmsg/frame_test.go
> +func Test_randID(t *testing.T) {
@ayuryshev It tests that an ID is generated correctly depending on if we need an initiator one or not.

2019-06-20 18:37 UTC, evanlinjin commented on pkg/dmsg/frame_test.go
> +func Test_randID(t *testing.T) {
@ayuryshev I'm sure that it is obvious to you how the test works. If you think the test can be improved, it is better to write that in a statement detailing your thoughts.

2019-06-21 06:33 UTC, ayuryshev commented on pkg/dmsg/transport.go
> +	inMx sync.RWMutex // protects 'inCh'
This mutex  is not needed.
It's used in `Transport.HandleFrame` and used incorrectly to remedy incorrect `select` statement.

After changing HandleFrame into:

```golang
func (tp *Transport) HandleFrame(f Frame) error {
	if tp.IsClosed() {
		return io.ErrClosedPipe
	}

	tp.inCh <- f
	return nil
```
Everything works

2019-06-21 06:37 UTC, ayuryshev commented on pkg/dmsg/transport.go
> +func (tp *Transport) HandleFrame(f Frame) error {
Look at my comment about `Transport.inMx`

2019-06-21 06:53 UTC, ayuryshev commented on pkg/dmsg/transport.go
> +	case <-tp.done:
I think it would be more safe to remove:
```golang
 case <-tp.done:
   return
```

and substitute it with check before `select`:

```golang
if tp.IsClosed() {
   return io.ErrClosedPipe
}
```

2019-06-21 06:56 UTC, ayuryshev commented on pkg/dmsg/transport.go
> +		case <-tp.done:
And here check for `case <-tp.done` would be better substituted with `if tp.IsClosed()`

2019-06-21 07:06 UTC, evanlinjin commented on pkg/dmsg/transport.go
> +	inMx sync.RWMutex // protects 'inCh'
The mutex is needed because `close(tp.inCh)` and `tp.inCh <- f` operations are not thread-safe.

"Everything works" is not good enough. You cannot ensure, with this statement, that you have tested all scenarios and conditions.

However, you can definitely say:
- I've noticed that doing the following changes still allows the system to work.
- I feel the `select` statement here is faulty, because we cannot guarantee that the `done` case will be selected when it's given that `done` is closed.

2019-06-21 07:08 UTC, evanlinjin commented on pkg/dmsg/transport.go
> +func (tp *Transport) HandleFrame(f Frame) error {
This comment is not constructive. I will resolve this thread.

2019-06-21 07:17 UTC, evanlinjin commented on pkg/dmsg/transport.go
> +	case <-tp.done:
@ayuryshev please review my most recent changes as I feel it is a more elegant solution: https://github.com/skycoin/skywire/pull/402/commits/e9e11d025b147d07d3d84d3472612cf564ed414c

2019-06-21 07:20 UTC, evanlinjin commented on pkg/dmsg/transport.go
> +		case <-tp.done:
As aforementioned, please check out my latest changes: https://github.com/skycoin/skywire/commit/e9e11d025b147d07d3d84d3472612cf564ed414c

2019-06-24 08:11 UTC, merged