added dockerfiles
skycoin/skywire-testnet pull request #472
Opened 2019-07-04 17:24 UTC by ivcosla

Dockerfiles for skywire nodes

2019-07-04 17:32 UTC, ivcosla commented
WIP until I figure out what is wrong with apps, which the node cannot find

2019-07-04 17:48 UTC, ayuryshev requested changes
Good. Some cleanup needed.

2019-07-04 17:48 UTC, ayuryshev commented on docker/images/builder/Dockerfile
> +RUN ./docker/images/builder/update.sh
Those 4 RUNs create 3 layers in image.
They could be aggregated into 
```
RUN [instruction_1] && [instruction_2] ... 
```

2019-07-04 17:48 UTC, ayuryshev commented on docker/images/builder/Dockerfile
> +RUN ./docker/images/builder/install.sh
There is no need in skywire to have separate update.sh and install.sh.
install.sh already has everything from update.sh.

2019-07-04 17:48 UTC, ayuryshev commented on docker/images/builder/Dockerfile
> +RUN apk add make
Separate RUN just to install make. Note that it will work only if apk  present

2019-07-04 17:48 UTC, ayuryshev commented on docker/images/builder/Dockerfile
> +RUN go build -mod=vendor -tags netgo -ldflags="-w -s" \
I would rather move it into compile.sh/build.sh - same as in skywire-services.

2019-07-04 17:48 UTC, ayuryshev commented on docker/images/node/Dockerfile
> +FROM ${builder} as builder
builder/Dockerfile could be merged with this Dockerfile.

Merge and add last line:
```
FROM base
```

2019-07-04 17:48 UTC, ayuryshev commented on docker/images/node/Dockerfile
> +COPY --from=builder /go/skywire/docker/images/builder/update.sh update.sh
Why update.sh needed in built image?

2019-07-05 09:27 UTC, ayuryshev commented on docker/images/node/update.sh
> +        apk add iproute2
`iproute2` second time here

2019-07-05 09:28 UTC, ayuryshev reviewed
Good

2019-07-05 10:59 UTC, ayuryshev approved these changes

2019-07-05 11:14 UTC, merged