Remove linter excluding rules, clean up code
skycoin/skywire-testnet pull request #481
Opened 2019-07-14 18:51 UTC by nkryuchkov

Closes #460.

Changes:
- Removed all linter excluding rules
- Removed all `nolint` comments except a couple of them that are really necessary
- Fixed all linter issues after removal
- Made some code cleanup
- Fixed issues found by `gocritic`, `scopelint`, `unconvert` linters

2019-07-15 09:44 UTC, Darkren requested changes
Overall it's a huge job done and done great, but I left some comments

2019-07-15 09:44 UTC, Darkren commented on internal/therealproxy/server_test.go
> +	l, err := net.Listen("tcp", "localhost:10081")
I'd suggest this to be implemented via `nettest`

2019-07-15 09:44 UTC, Darkren commented on pkg/httputil/httputil.go
> +	if pretty, err := BoolFromQuery(r, "pretty", false); err == nil && pretty {
Shouldn't this error be logged?

2019-07-15 09:44 UTC, Darkren commented on pkg/setup/node_test.go
> +	testing *testing.T
It may ruin tests if we create a single `mockNode` and run several `t.Run` cases against it

2019-07-15 09:48 UTC, nkryuchkov commented on pkg/setup/node_test.go
> +	testing *testing.T
@Darkren well spotted, I'm going to get rid of `testing *testing.T` field

2019-07-15 13:12 UTC, nkryuchkov commented on pkg/httputil/httputil.go
> +	if pretty, err := BoolFromQuery(r, "pretty", false); err == nil && pretty {
@Darkren Probably a good idea, thanks. Added some logging.

2019-07-15 13:23 UTC, nkryuchkov commented on internal/therealproxy/server_test.go
> +	l, err := net.Listen("tcp", "localhost:10081")
@Darkren Good idea. Done.

2019-07-17 09:50 UTC, evanlinjin commented on cmd/apps/therealproxy-client/therealproxy-client.go
> +			log.Println("Failed to close app: ", err)
No need for space after `app: `. It is `Println` after all.

2019-07-17 09:57 UTC, evanlinjin commented on internal/httpauth/client.go
> +	if resp != nil {
Shouldn't we check the `err` first?

2019-07-17 10:00 UTC, evanlinjin commented on internal/httpauth/client_test.go
> +	if b != nil {
Shouldn't we be checking the error here first?

2019-07-17 10:00 UTC, nkryuchkov commented on internal/httpauth/client.go
> +	if resp != nil {
@evanlinjin Both `resp` and `err` may be non-nil in case of a redirection failure.
Source: http://devs.cloudimmunity.com/gotchas-and-common-mistakes-in-go-golang/index.html#close_http_resp_body

2019-07-17 10:01 UTC, nkryuchkov commented on cmd/apps/therealproxy-client/therealproxy-client.go
> +			log.Println("Failed to close app: ", err)
@evanlinjin Well spotted, thanks.

2019-07-17 10:24 UTC, nkryuchkov commented on internal/httpauth/client_test.go
> +	if b != nil {
@evanlinjin Actually, this looks strange, I'm going to rewrite it.

2019-07-17 15:20 UTC, evanlinjin approved these changes

2019-07-17 15:20 UTC, evanlinjin commented on internal/httpauth/client_test.go
> +	if b != nil {
Check error first.

2019-07-17 15:53 UTC, merged