[WIP] Routing data type cleanup
skycoin/skywire-testnet pull request #482
Opened 2019-07-15 06:50 UTC by Darkren

Fixes #444 

- `app.Addr` and `app.LoopAddr` were combined and moved to `routing.Addr`
- type `Port uint16` was introduced
- `setup.LoopData` was refactored to use `routing.Addr` and moved to `routing.LoopData`
- `routing.Loop` and `routing.LoopDescriptor` are separate type now

2019-07-15 19:12 UTC, nkryuchkov approved these changes
Looks good to me, nice job! However, I haven't tested it.

2019-07-16 10:01 UTC, ayuryshev requested changes
I suppose that this cleanup could be improved further with another step - changing signatures of  functions that use types `*routing.Addr`, `(routing.Loop` and `*routing.LoopDescriptor` for params to signatures without pointers.

E.g.
```golang 
type Dialer interface{
   Dial(raddr routing.Addr) (net.Conn, error)
   // instead of Dial(raddr *routing.Addr) (net.Conn, error)
}
```
This way it will automatically exclude posibilities for data races.

2019-07-16 10:01 UTC, ayuryshev commented on internal/therealssh/client.go
>  type Dialer interface {
I have questions about Dialer interface:

I see 2 types that implements Dialer interface: 
- `therealsssh.pipeDialer`  - used in tests only
- `app.App` - in application code

`Dialer` as argument is used only in `therelealssh.NewClient`

Question 1: Why this interface made public? Is it intended to use it outside `therealssh` ?
Question 2: In case  `Dialer` is intended to be used outside: maybe it's makes sense to move it in `app` package?

2019-07-16 10:01 UTC, ayuryshev commented on internal/therealssh/client.go
> +	Dial(raddr *routing.Addr) (net.Conn, error)
Why not define without pointer as `Dial(raddr routing.Addr) (net.Conn, error)` ? 

I see that (almost) everywhere that `raddr` is constructed on place in a manner: 
`Dial(&routing.Addr{pk, port})`.  

It's a possible place for data races

2019-07-16 10:01 UTC, ayuryshev commented on internal/therealssh/client.go
> +		conn, err = c.dialer.Dial(&routing.Addr{PubKey: remotePK, Port: Port})
And here is an example of `*routing.Addr` construction on place.
Is it possible to change signature of `Dial` to `func(routing.Addr) (net.Conn,error)` ?

2019-07-16 10:01 UTC, ayuryshev commented on pkg/routing/addr.go
> +type Addr struct {
Question about lifecyle for values of `Addr` type:
- Is this type intended to be used as immutable: created once and then never changed internals?
- Or intentions is to use as:
```golang
adrr:= Addr{Port(13)}
go somefunc(*addr)
addr.Port = Port{14}
```
?

So far I found only one place of possible mutation: `app.Protocol.Send` where pointer to Addr passed as `interface{}`

Question is not about `Addr` type itself but about most methods that use `*routing.Addr` params

2019-07-16 10:01 UTC, ayuryshev commented on pkg/routing/loop.go
>  type Loop struct {
The same question as for `Addr` arises for `Loop` and `LoopDescriptor`:
Are those types intended as mostly immutable or it's intended usage that internal content could be changed during lifetime?

In case it intended as mostly immutable - why not use them in functions as values without pointers?

2019-07-16 10:40 UTC, evanlinjin commented on internal/therealssh/client.go
>  type Dialer interface {
`Dialer` is not intended to be used publicly.

2019-07-16 10:42 UTC, evanlinjin commented on internal/therealssh/client.go
> +	Dial(raddr *routing.Addr) (net.Conn, error)
Yes it will be better to be a non-pointer.

2019-07-16 10:42 UTC, evanlinjin commented on internal/therealssh/client.go
> +		conn, err = c.dialer.Dial(&routing.Addr{PubKey: remotePK, Port: Port})
Yes.

2019-07-16 10:46 UTC, evanlinjin commented on pkg/routing/addr.go
> +type Addr struct {
It is better to be used as a non-pointer. Thanks for pointing this out. @Darkren would it be too much of a hassle to make the relevant changes?

2019-07-16 10:46 UTC, evanlinjin commented on pkg/routing/loop.go
>  type Loop struct {
Immutable.

2019-07-16 10:47 UTC, evanlinjin reviewed
Looks mostly good. Would merge after the changing the associated structures to be immutable (as mentioned by @ayuryshev ).

2019-07-16 10:49 UTC, Darkren commented on pkg/routing/addr.go
> +type Addr struct {
@evanlinjin I think from this point of view this should be done regardless of time. I don't think this will take too much anyway, I'll do it

2019-07-16 12:22 UTC, ayuryshev commented on internal/therealssh/client.go
>  type Dialer interface {
If that's the case - why not `type dialer interface`?

2019-07-17 07:22 UTC, Darkren commented on internal/therealssh/client.go
>  type Dialer interface {
I also moved a bit further, made `routing.LoopDescriptor` and `routing.LoopData` being passed as non-pointers too. I believe that this is appropriate too. So, the only thing left is this question about `dialer` @evanlinjin

2019-07-17 08:08 UTC, evanlinjin commented on internal/therealssh/client.go
>  type Dialer interface {
@Darkren let's make `Dialer` private as @ayuryshev suggested.

2019-07-17 08:25 UTC, Darkren commented on internal/therealssh/client.go
>  type Dialer interface {
@evanlinjin made it unexported, also moved to a separate `dialer.go` file

2019-07-17 09:10 UTC, evanlinjin approved these changes
Everything looks good and seems to be working fine according to my tests.

2019-07-17 09:13 UTC, merged