[WIP] Feature: TCPFactory/TCPTransport instead of dmsg
skycoin/skywire-testnet pull request #503
Opened 2019-07-25 18:53 UTC by ayuryshev

It's WIP.
Just compiled and passes regular tests.

Closes: #501

2019-07-29 09:33 UTC, jdknives requested changes

2019-07-29 09:33 UTC, jdknives commented on pkg/setup/node.go
> +	messenger transport.Factory
The setup node is supposed to use dmsg exclusively and directly. The communication between the visor and the setup node should not use TCP transport.

2019-08-12 10:47 UTC, evanlinjin commented on pkg/router/router.go
> +		_, err := r.tm.CreateSetupTransport(context.Background(), raddr.PubKey, "tcp-transport")
`dmsg` is to be used with `SetupNode` always.

2019-08-12 10:52 UTC, evanlinjin commented
Just a thought, let's split this PR into two.
- PR1: Implement the ability to choose between transport types for estabilishing data transports.
- PR2: Testing stuff.

Let's make this PR be `PR1` so we can have it merged faster.

2019-09-04 08:20 UTC, closed without merging