[WIP] Feature/therealssh pty
skycoin/skywire-testnet pull request #505
Opened 2019-08-02 16:53 UTC by ivcosla

Closes #500

2019-08-09 14:38 UTC, nkryuchkov approved these changes
Looks good to me. Great job!

2019-08-09 14:38 UTC, nkryuchkov commented on pkg/therealssh/pty_test.go
> +	b := make([]byte, 6024)
Does `6024` mean anything or is it just an arbitrary value?

2019-08-09 18:43 UTC, Darkren requested changes
Otherwise, great job!

2019-08-09 18:43 UTC, Darkren commented on pkg/therealssh/pty_test.go
> +		require.NoError(t, err)
I think the error should be better passed outside of a goroutine and checked there. This one is probably won't work

2019-08-11 05:49 UTC, evanlinjin commented on pkg/therealssh/pty_test.go
> +		require.NoError(t, err)
Yes, we should never use `require` or `assert` library inside a go routine as it may result in a race condition.

2019-08-11 06:50 UTC, evanlinjin reviewed
Good stuff! These are mode two cents for code quality. I'll actually test it out next.

2019-08-11 06:50 UTC, evanlinjin commented on pkg/therealssh/channel.go
> +		_, err = sshCh.Write(out)
Reusing `err` may result in race condition as we are reading `err` in the return statement later. I would add a colon:
```golang
_, err := sshCh.Write(out)
```

2019-08-11 06:50 UTC, evanlinjin commented on pkg/therealssh/session.go
> +	var err error
I don't think we need this.

2019-08-11 22:20 UTC, ivcosla commented on pkg/therealssh/pty_test.go
> +	b := make([]byte, 6024)
Arbitrary value. Wanted to make sure it was big enough

2019-08-11 22:23 UTC, ivcosla commented on pkg/therealssh/session.go
> +	var err error
We need it to overwrite `command`. Otherwise in line 86 `command` is taken as a new variable if we use a colon in there.

2019-08-11 22:29 UTC, ivcosla commented on pkg/therealssh/pty_test.go
> +		require.NoError(t, err)
`server.Serve` is not returning after neither `server.Close` or `dial/acceptConn.Close`, so for now I just turned off the linter.

2019-08-11 22:32 UTC, ivcosla commented
Commented this test https://github.com/skycoin/skywire/pull/505/files#diff-858b5f577c60d24dea6b5c413b8452b3R17 since it's messing with parallel execution. Only one rpc client with the same name can exist at a time, so when both tests are launched one fails.

If you think this test is not needed since it's logic is also tested in the next test let me know and if the PR is approved I will just delete it and merge.

2019-08-12 07:35 UTC, evanlinjin commented on pkg/therealssh/session.go
> +	var err error
Okay makes sense.

2019-08-12 11:32 UTC, merged