[WIP] Make route establishment asynchronous
skycoin/skywire-testnet pull request #519
Opened 2019-08-18 16:39 UTC by Darkren

Fixes #506 

Made route establishment procedure asynchronous. 
- Route establishment procedure was divided into 2 steps:
    1. Request registration ID
    2. Apply rule
- Rule was extended to hold `registration ID` field
- The route establishment procedure itself was put in goroutines (one for each `visor` node applying rule). Any error during route setup cancels the whole procedure
- Tests were adjusted

2019-08-19 06:26 UTC, evanlinjin requested changes
Good stuff. Excited for these changes. Please check my comments, more is coming.

2019-08-19 06:26 UTC, evanlinjin commented on pkg/router/route_manager.go
> +<<<<<<< HEAD
Please fix.

2019-08-19 06:26 UTC, evanlinjin commented on pkg/router/route_manager.go
> +func (rm *routeManager) Serve(rwc io.ReadWriteCloser) error {
I've renamed this to `handleSetupConn` and `Serve()` should run a loop. Please check: https://github.com/skycoin/skywire/blob/mainnet-milestone1/pkg/router/route_manager.go

2019-08-19 06:26 UTC, evanlinjin commented on pkg/setup/node.go
> +		var regIDChIn, regIDChOut chan routing.RouteID
For the above, can you please rename `idx` to `i`. Thanks!

2019-08-19 06:26 UTC, evanlinjin commented on pkg/setup/node.go
> +	// Goroutine[idx] requests visor node for a registration ID. It passes this registration ID through a chan to
`idx` -> `i` (as it's represented typically in Golang).

2019-08-19 06:26 UTC, evanlinjin commented on pkg/setup/node.go
> +		var nextTransport uuid.UUID
rename is `nextTpID`

2019-08-19 07:25 UTC, evanlinjin requested changes
As a general comment for variable names: Golang style generally prefers shorter variable names.
- Public key: `pk`
- Route: `rt`.
- Route ID: `rtID`
- Transport: `tp`
- Transport ID: `tpID`
- Index: `i`
- initiator: `init`
- responder: `resp`

(We can discuss each of these cases, but this is what I have been following with my own naming conventions).

Also it will be good to have the setup procedure documented. For example, I have no idea why `// adding rule for initiator must result with a route ID` :sweat_smile:

Other than the comments I have made, the code looks good. The next steps is testing and to ensure that it works in interactive environment.

Good stuff!

2019-08-19 07:25 UTC, evanlinjin commented on pkg/routing/rule.go
> +func (r Rule) RegistrationID() RouteID {
What was the intention behind creating a separate name for `RouteID`? How is this different to the `RouteID` which is used as the key to routing rules?

2019-08-19 07:25 UTC, evanlinjin commented on pkg/setup/node.go
> +	r := make(routing.Route, len(route)+1)
Why have we created a second `routing.Route` variable?

2019-08-19 07:25 UTC, evanlinjin commented on pkg/setup/node.go
> +	routeID := <-resultingRouteIDCh
From my understanding, this may lead to hang. Have a select statement with `ctx.Done()` maybe.

2019-08-19 07:25 UTC, evanlinjin commented on pkg/router/route_manager.go
> +func (rm *routeManager) Serve(rwc io.ReadWriteCloser) error {
And get rid of the `<<<<<<< HEAD`s :smile:

2019-08-19 07:28 UTC, Darkren commented on pkg/setup/node.go
> +	// Goroutine[idx] requests visor node for a registration ID. It passes this registration ID through a chan to
@evanlinjin I tried to preserve namings as much as I could, probably not the best idea. I'll change this

2019-08-19 07:31 UTC, Darkren commented on pkg/routing/rule.go
> +func (r Rule) RegistrationID() RouteID {
@evanlinjin There is already route ID there. It servers as a `respRouteID` for app rules and as a `nextRouteID` for forward rules. It's not the ID which is used as a key to store this particular rule inside a visor node. That was the biggest trick there. We make a first request to visor node to request a free route ID for the rule. We use this route ID as registration ID for this rule and we use the same route ID as a `nextRouteID/respRouteID` for the previous visor node along the route. That's why I decided to distinguish these IDs, with the same name it becomes hell to understand what's going on there

2019-08-19 07:34 UTC, Darkren commented on pkg/setup/node.go
> +	r := make(routing.Route, len(route)+1)
@evanlinjin I'm not sure why it'd been here before, while doing these changes I realised that it's not really needed in a synchronous version. But I needed one to start the goroutines simpler and avoid code duplication. And also not to interfere with the original contents of the route, to avoid the side effect of the func

2019-08-19 07:34 UTC, Darkren commented on pkg/setup/node.go
> +	routeID := <-resultingRouteIDCh
Much appreciate, will do

2019-08-19 07:35 UTC, evanlinjin commented on pkg/routing/rule.go
> +func (r Rule) RegistrationID() RouteID {
@Darkren thanks for the explanation, that makes sense. However, I'm still confused as to why we need to modify the `routing.Rule` type?

2019-08-19 07:37 UTC, evanlinjin commented on pkg/setup/node.go
> +	r := make(routing.Route, len(route)+1)
@Darkren let's make a `"TODO: I-don't-know-why-this-is-here` comment.

2019-08-19 07:37 UTC, evanlinjin commented on pkg/setup/node.go
> +	r := make(routing.Route, len(route)+1)
I'm being serious btw.

2019-08-19 07:38 UTC, Darkren commented on pkg/routing/rule.go
> +func (r Rule) RegistrationID() RouteID {
@evanlinjin Well, when we get the free route ID from the visor node, we need to send it the rule and tell which route ID should be used to register this rule. Modifying the rule type was straightforward and the simplest solution with regards to network load. From the visor's perspective we need to deal with a lot of requests simultaneously, if we receive a lot of rule at once, we need to know IDs for these rules

2019-08-19 07:42 UTC, Darkren commented on pkg/setup/node.go
> +	r := make(routing.Route, len(route)+1)
@evanlinjin I actually know the purpose of this array now, I'm running goroutines below, one goroutine for each element of this array. In mainnet we have a loop over this route and apply rule on each iteration. After this loop we apply a rule for the initiator node. In this implementation there is no necessity to have this a separate step imo, that's why I put it into the loop itself into the dedicated goroutine. The code for initiator is just the same as for every other node, so, making this a separate step is just duplicating the code

2019-08-19 07:43 UTC, evanlinjin commented on pkg/routing/rule.go
> +func (r Rule) RegistrationID() RouteID {
So when a visor node receives a rule, it checks the Registration ID to know which request is satisfied? Would it be better to call it `RequestRouteID`?

2019-08-19 07:45 UTC, Darkren commented on pkg/routing/rule.go
> +func (r Rule) RegistrationID() RouteID {
@evanlinjin Yes. I may call it a `RequestRouteID`, np, it's a subject for discussion. My main intent was to disinguish it from the original `routeID` inside a rule, the naming can be whatever fits best

2019-08-19 07:47 UTC, evanlinjin commented on pkg/routing/rule.go
> +func (r Rule) RegistrationID() RouteID {
Fair enough, I see your point. Let's rename to `RequestRouteID` as the idea of "Registration" may be confused with other things.

2019-08-19 07:47 UTC, evanlinjin commented on pkg/setup/node.go
> +	r := make(routing.Route, len(route)+1)
@Darkren do you mean we can get rid of it?

2019-08-19 07:48 UTC, Darkren commented on pkg/setup/node.go
> +	r := make(routing.Route, len(route)+1)
@evanlinjin Well, yes, but we'll still be looping over the original route plus one iteration for the initiating node

2019-08-19 07:50 UTC, evanlinjin commented on pkg/setup/node.go
> +	r := make(routing.Route, len(route)+1)
Would it be safe to modify the original `route` variable? Remember to put a comment above such a modification step (if needed) to explain the purpose of modification.

2019-08-19 07:52 UTC, Darkren commented on pkg/setup/node.go
> +	r := make(routing.Route, len(route)+1)
@evanlinjin I'll need to check the code base to be certain about safety. Also even if it's safe now, we can't guarantee the same for future changes. That's why I created new variable for this purpose. I think I can get rid of it and run a separate goroutine manually without modifying the original route, I'm not a fan of this, consequences may be tough. I'll see what I can do

2019-08-19 07:59 UTC, evanlinjin commented on pkg/setup/node.go
> +	r := make(routing.Route, len(route)+1)
@Darkren I see what you mean. Let's do this:
```golang
route = append(&routing.Hop{
		Transport: route[0].Transport,
		To:        route[0].From,
	}, route[1:]...)
```

2019-08-19 08:01 UTC, evanlinjin commented on pkg/setup/node.go
> +	r := make(routing.Route, len(route)+1)
I see, sorry I deleted my previous comment as it was a mistake. Let's create a comment above it detailing the intentions behind it.

2019-08-19 17:03 UTC, Darkren commented on pkg/setup/node.go
> +	r := make(routing.Route, len(route)+1)
@evanlinjin I left some comments there and also heavily commented the whole function. Please check it out and tell me if it needs any further clarifications

2019-08-20 07:58 UTC, Darkren commented on pkg/setup/node.go
> +	routeID := <-resultingRouteIDCh
@evanlinjin I create inner context from the ctx passed to the func. In case the outer ctx gets cancelled, the inner one gets too. In this case the whole procedure gets cancelled. Right after the goroutines stop there is a check for any errors along the way. If there are any - func returns immideately. If there was none, we execute this line you mentioned above. At this part of execution the value is guaranteed to be there. I added more comments at this part, please check if they're sufficient

2019-08-20 07:59 UTC, evanlinjin commented on pkg/setup/node.go
> +	routeID := <-resultingRouteIDCh
@Darkren Thanks for the update, will look after meeting.

2019-08-22 07:03 UTC, evanlinjin commented on pkg/setup/node.go
> +		To:        route[0].From,
Why do we need to swap the `To` and `From` fields and get rid of the `To` field for the initiating element?

2019-08-22 07:19 UTC, evanlinjin commented on pkg/setup/node.go
> +	cancellableCtx, cancel := context.WithCancel(ctx)
```golang
ctx, cancel := context.WithCancel(ctx)
```
Will be fine.

2019-08-22 07:21 UTC, Darkren commented on pkg/setup/node.go
> +		To:        route[0].From,
@evanlinjin That's because we're iterating over `visor` nodes we send requests to. For each node we use the `To` field. But the initiating node stands aside, there is no initiating node in the `route`. So, we expand the original rotue by adding the initiating node first in the list and we fill `To` with `From` from the first `visor` node along the route. This corresponds to the initiating node

2019-08-22 07:25 UTC, evanlinjin commented on pkg/setup/node.go
> +	var cancelOnce sync.Once
```golang
func main() {
	ctx := context.Background()
	ctx, cancel := context.WithCancel(ctx)

	const n = 1000000
	wg := new(sync.WaitGroup)
	wg.Add(n)

	for i := 0; i < n; i++ {
		go func(i int) {
			cancel()
			wg.Done()
		}(i)
	}

	<-ctx.Done()
	fmt.Println("Done!")
	wg.Wait()
}
```
I just tested `ctx`, and it seems that this is not needed.

2019-08-22 07:27 UTC, Darkren commented on pkg/setup/node.go
> +	cancellableCtx, cancel := context.WithCancel(ctx)
@evanlinjin this way we're overwriting the new context to the original passed to the whole func

2019-08-22 07:32 UTC, Darkren commented on pkg/setup/node.go
> +	cancellableCtx, cancel := context.WithCancel(ctx)
@evanlinjin I'll test it myself once again, but I feel like the `cancellationCtx` is used only within the func to stop the internal process. And if we call `cancel`, the outer processes using the original `ctx` won't be affected. But if the original `ctx` was also created `WithCancel` and some outer code calls the corresponding `cancel` func for the outer `ctx` the whole func will be cancelled correctly. Well, at least I counted on that behavior, I'll check it out

2019-08-22 10:46 UTC, merged