[WIP] Feature/226 manaager node backend additions
skycoin/skywire-testnet pull request #521
Opened 2019-08-20 11:54 UTC by ivcosla

Implements #226

2019-08-22 17:11 UTC, nkryuchkov commented on cmd/apps/skychat/chat.go
> +	fmt.Println(os.Args)
Does this line have any purpose? Looks like it may be a forgotten debug print.

2019-08-22 17:11 UTC, nkryuchkov commented on cmd/apps/skychat/chat.go
> +	"github.com/skycoin/skycoin/src/util/logging"
Could you please sort imports here?

2019-08-22 17:11 UTC, nkryuchkov commented on cmd/apps/skychat/chat.go
> +	log, _ = app.NewLogger(appName, os.Args)
Could we handle a probable error here?

2019-08-22 17:11 UTC, nkryuchkov commented on cmd/skywire-cli/commands/node/app.go
> +	Short: "Gets logs from given app since RFC3339Nano-formated timestamp",
Could you please change `formated` to `formatted`?

2019-08-22 17:11 UTC, nkryuchkov commented on pkg/app/log.go
> +	"github.com/skycoin/skycoin/src/util/logging"
Could you please format imports in this file?

2019-08-22 17:11 UTC, nkryuchkov commented on pkg/app/log_store.go
> +func (l *boltDBappLogs) Write(p []byte) (int, error) {
What do you think of checking the length of `p` here and return an error if the function is misused?

2019-08-22 17:11 UTC, nkryuchkov commented on pkg/app/log_store.go
> +func iterateFromKey(c *bbolt.Cursor, logs *[]string) error {
Could we rewrite `iterateFromKey` and `iterateFromBeginning` in a way that it returns logs along with an error instead of appending them by pointer?

2019-08-22 17:11 UTC, nkryuchkov commented on pkg/app/log_store.go
> +
Could you please remove the empty line here?

2019-08-22 17:11 UTC, nkryuchkov commented on pkg/app/log_store_test.go
> +	"github.com/stretchr/testify/require"
Could you please sort imports here?

2019-08-22 17:11 UTC, nkryuchkov commented on pkg/app/log_test.go
> +	"github.com/skycoin/skycoin/src/util/logging"
Could you please sort imports here?

2019-08-22 17:11 UTC, nkryuchkov commented on pkg/app/log_test.go
> +		b := make([]byte, 51)
Why does `b` have the size of `51` here?

2019-08-22 17:11 UTC, nkryuchkov commented on pkg/hypervisor/hypervisor.go
> +	healthStatuses := make([]*VisorHealth, len(m.nodes))
You probably meant `healthStatuses := make([]*VisorHealth, 0, len(m.nodes))` here.

2019-08-22 17:11 UTC, nkryuchkov commented on pkg/visor/rpc.go
> +	"net/http"
Could you please sort imports here?

2019-08-22 17:11 UTC, nkryuchkov commented on pkg/visor/rpc_client.go
> +		TransportDiscovery: 200,
`http.StatusOK` might be more readable here

2019-08-23 07:44 UTC, evanlinjin requested changes
Good stuff. Some comments.

2019-08-23 07:44 UTC, evanlinjin commented on pkg/app/log.go
> +func NewLogger(appName string, args []string) (*logging.MasterLogger, []string) {
Why would we use this as apposed to `(*App).LoggerFromArguments()`?

2019-08-23 07:44 UTC, evanlinjin commented on pkg/app/log_store.go
> +func iterateFromKey(c *bbolt.Cursor, logs *[]string) error {
@nkryuchkov How do you suggest we do this? And how should it be used in `LogsSince`?

2019-08-23 07:44 UTC, evanlinjin commented on pkg/app/log_test.go
> +		t.Fail()
We need to use `t.FailNow()` or else it does not return. A better method would be to use `require.NoError()` to be consistent.

2019-08-23 07:44 UTC, evanlinjin commented on pkg/app/log_test.go
> +		b := make([]byte, 51)
From my understanding, this is just an arbitrary value to contain the reads. If not, @ivcosla, please create a constant.

2019-08-23 07:44 UTC, evanlinjin commented on pkg/app/log_test.go
> +func TestWriteLog(t *testing.T) {
Some comments to describe what is being tested will be helpful.

2019-08-23 07:44 UTC, evanlinjin commented on pkg/app/log_test.go
> +	fmt.Printf("%#v", string(res))
Should we check this output?

2019-08-23 07:44 UTC, evanlinjin commented on pkg/hypervisor/hypervisor.go
> +	healthStatuses := make([]*VisorHealth, len(m.nodes))
We should probably write tests for these endpoints.

2019-08-23 07:47 UTC, ivcosla commented on cmd/apps/skychat/chat.go
> +	fmt.Println(os.Args)
Yes just a print, that I should remove when work on the PR is finished.

2019-08-23 07:52 UTC, ivcosla commented on cmd/apps/skychat/chat.go
> +	log, _ = app.NewLogger(appName, os.Args)
It's not an error. Second argument is `[]string` which is `os.Args` with the first argument stripped to make it more transparent to use for the user. But this function signature requires rethinking, I'm not happy with it. If there is an error inside it panics.

Ideally, I think we should return 3 arguments during `app.Setup`-> `(*App, *logging.MasterLogger, error)`. The idea is that the user must always get the logger to prevent scenarios in which he would forgot to create a logger and thus more likely to use it. I don't want to embed it in `*App` since the logger should be available at app setup time, in case that an error is returned an app is nil the logger should still be used to print the fatal error so the hypervisor can fetch it.

2019-08-23 07:54 UTC, ivcosla commented on pkg/app/log_store.go
> +func (l *boltDBappLogs) Write(p []byte) (int, error) {
I'm not sure about this, since `Write` is called from `*logging.MasterLogger`I'm not sure which misused there might be. An empty log maybe?, is it to be discarded or still persisted for hypervisor to fetch?.

But I agree should be checked in case that there might be a misuse. Do you have any other scenario in mind?

2019-08-27 15:40 UTC, ivcosla commented
There are linter errors preventing the PR to pass tests on travis. Those errors belong to other packages and should be fixed in a different PR.

2019-08-27 22:21 UTC, nkryuchkov commented
Linter errors will be fixed in https://github.com/skycoin/skywire/pull/537

2019-08-28 10:24 UTC, nkryuchkov commented on cmd/apps/skychat/chat.go
> +	log, _ = app.NewLogger(appName, os.Args)
@ivcosla Sorry, I didn't pay enough attention here and assumed that it returns a value and an error.

2019-08-28 10:31 UTC, nkryuchkov commented on pkg/app/log_store.go
> +func (l *boltDBappLogs) Write(p []byte) (int, error) {
@ivcosla It may be misused if `len(p) < 37`. I think this may happen if logger settings omit timestamp or specify another log format. Not sure if it may happen, but this may improve robustness. I'd add the following:
```suggestion
if len(p) < 37 {
	return 0, io.ErrShortBuffer
}
```

2019-08-28 10:41 UTC, nkryuchkov commented on pkg/app/log_store.go
> +func iterateFromKey(c *bbolt.Cursor, logs *[]string) error {
@evanlinjin I would write the function this way:
```
func iterateFromKey(c *bbolt.Cursor) ([]string, error) {
	logs := make([]string, 0)
	for k, v := c.Next(); k != nil; k, v = c.Next() {
		logs = append(logs, string(v))
	}
	return logs, nil
}
```
And then append the returned value to the `logs` variable outside the function.

On the one hand, it would decrease the performance a bit. On the other hand, I think it would be more readable.

2019-08-28 11:17 UTC, evanlinjin commented on pkg/app/log_store.go
> +func iterateFromKey(c *bbolt.Cursor, logs *[]string) error {
I think that is better.

2019-09-03 17:17 UTC, nkryuchkov commented on pkg/app/log_store.go
> +			panic(err)
Is there a reason why panicking instead of returning an error is preferred here and in `Store` method?

2019-09-03 17:17 UTC, nkryuchkov commented on cmd/skywire-cli/commands/node/app.go
> +		if args[1] == "beginning" {
What do you think of extracting the `"beginning"` constant here?

2019-09-03 17:17 UTC, nkryuchkov commented on pkg/hypervisor/hypervisor.go
> +			return
Could we get rid of it? Looks redundant.

2019-09-03 17:17 UTC, nkryuchkov commented on pkg/hypervisor/hypervisor.go
> +			httputil.WriteJSON(w, r, http.StatusInternalServerError, err)
I think we need a return statement here, because `httputil.WriteJSON(w, r, http.StatusOK, u)` would be also executed.

2019-09-06 07:26 UTC, evanlinjin commented
What's the situation with this PR?

2019-09-06 08:15 UTC, ivcosla commented
It can be merged after conflicts are fixed

2019-09-06 08:19 UTC, merged