Change rule expiry to keep-alive
skycoin/skywire-testnet pull request #527
Opened 2019-08-22 15:32 UTC by Darkren

Modified rule to contain `KeepAlive` field instead of `ExpiresAt` also adjusting the client code and tests

2019-08-23 06:47 UTC, evanlinjin requested changes
Good work. Just some comments here and there.

2019-08-23 06:47 UTC, evanlinjin commented on pkg/router/managed_routing_table.go
>  	rt.mu.Lock()
We should also lock the `rt.Table.AddRule()` to ensure the entire operation is atomic (as there is a very small possibility that the added rule is deleted immediately by `Cleanup`).

2019-08-23 06:47 UTC, evanlinjin commented on pkg/router/router.go
> +	RouteKeepAlive = 2 * time.Hour
Rename to `DefaultRouteKeepAlive`.

2019-08-23 06:47 UTC, evanlinjin commented on pkg/visor/rpc_client.go
> +	ruleKeepAlive := 24 * time.Hour
Use `router.DefaultRouteKeepAlive`.

2019-08-23 12:14 UTC, Darkren commented on pkg/router/managed_routing_table.go
>  	rt.mu.Lock()
@evanlinjin fair. Fixed this one by putting `AddRule` and `DeleteRules` calls under the lock, please check out if it's appropriate

2019-08-23 12:44 UTC, evanlinjin commented on pkg/router/managed_routing_table.go
>  	rt.mu.Lock()
We need to move `rt.mu.Lock()` to line `31`. There is still a possibility that `Cleanup` will trigger on execution hits line `32`, hence, deleting the rule as soon as it's created.

2019-08-23 12:53 UTC, Darkren commented on pkg/router/managed_routing_table.go
>  	rt.mu.Lock()
@evanlinjin I'm sorry, made a stupid move. I made `Rule` atomic instead of `AddRule` just confused methods. However, I made `AddRule` atomic now. And the question is, should `Rule` also be atomic as it is now?

2019-08-23 12:54 UTC, evanlinjin commented on pkg/router/managed_routing_table.go
>  	rt.mu.Lock()
Ahh I see, that makes sense. Yeah sure, let's keep it as is. Now we have consistency across the methods.

2019-08-26 03:06 UTC, evanlinjin requested changes
Looks good. Just one thing.

2019-08-26 03:06 UTC, evanlinjin commented on pkg/router/managed_routing_table.go
> +			expiredIDs = append(expiredIDs, routeID)
We need to have `delete(rt.activity, routeID)` somewhere.

2019-08-26 04:38 UTC, Darkren commented on pkg/router/managed_routing_table.go
> +			expiredIDs = append(expiredIDs, routeID)
Fair

2019-09-04 09:37 UTC, evanlinjin approved these changes

2019-09-04 09:42 UTC, merged