Milestone-1 TCP-Transport.
skycoin/skywire-testnet pull request #536
Opened 2019-08-27 10:35 UTC by ayuryshev

Excluding the last task defined  in https://github.com/skycoin/skywire/issues/501 - everything is completed.
It was already done by most part a long time before.
The most hard part is in the last task.

2019-08-27 15:54 UTC, evanlinjin requested changes

2019-08-27 15:54 UTC, evanlinjin commented on pkg/snet/network.go
> +	LocalTCPAddress string
Rename to `TCPLocalAddr`

2019-08-27 15:54 UTC, evanlinjin commented on pkg/snet/network.go
> +	PubKeyFile      string
Rename to `TCPPubKeyFile`

2019-08-27 15:54 UTC, evanlinjin commented on pkg/snet/network.go
> +	TCPType  = "tcptr"
Should be `tcp`

2019-08-27 15:54 UTC, evanlinjin commented on pkg/snet/network.go
> +func (n *Network) TCP() *TCPFactory {
Put this on line `107` to keep things orderly.

2019-08-27 15:54 UTC, evanlinjin commented on pkg/snet/tcp_transport.go
> +// +build !no_ci
Rename file to `tcp.go`. `Transport` is no longer an interface, but something that wraps `net.Conn`.

2019-08-27 15:54 UTC, evanlinjin commented on pkg/snet/tcp_transport.go
> +func (t *memPKTable) RemotePK(address string) cipher.PubKey {
Have this return `(cipher.PubKey, bool)`

2019-08-27 15:54 UTC, evanlinjin commented on pkg/snet/tcp_transport.go
> +	return "tcp-transport"
`"tcp"` is fine. Better to use the defined constant though.

2019-08-27 15:54 UTC, evanlinjin commented on pkg/snet/tcp_transport.go
> +// +build !no_ci
I think it is best to put this in a separate package `/pkg/snet/stcp`.

2019-08-27 15:54 UTC, evanlinjin commented on pkg/snet/tcp_transport.go
> +	RemoteAddr(remotePK cipher.PubKey) string
Why have we decided to use `string` instead of `net.TCPAddr`?

2019-08-27 15:54 UTC, evanlinjin commented on pkg/snet/tcp_transport.go
> +func memoryPubKeyTable(entries map[cipher.PubKey]string) *memPKTable {
Rename to `makeMemPKTable` to be consistent.

2019-08-27 15:54 UTC, evanlinjin commented on pkg/snet/tcp_transport.go
> +		reverse[addr.IP.String()] = k
Why are we using purely IP? Can we just use tcp address with `host:port`?

2019-08-27 15:54 UTC, evanlinjin commented on pkg/snet/tcp_transport.go
> +func MemoryPubKeyTable(entries map[cipher.PubKey]string) PubKeyTable {
`MakeMemoryPubKeyTable`

2019-08-27 17:09 UTC, ayuryshev commented on pkg/snet/tcp_transport.go
> +		reverse[addr.IP.String()] = k
It was my first thought too.
But then I remembered/encountered that for dialling side an ephemereal port is assigned. 
In the case when N nodes are dialling to single node that accepts connections - all diallers will have different ephemereal port.
So PK<==>IP  is simplest (and maybe the only practical) decision.

2019-08-27 17:37 UTC, ayuryshev commented on pkg/snet/tcp_transport.go
> +// +build !no_ci
Renamed.
About separate package: `net` from stdlib uses only one nesting level and covers all types of TCP/IP. I propose to stick with this example.

2019-08-27 17:56 UTC, ayuryshev commented on pkg/snet/tcp_transport.go
> +	RemoteAddr(remotePK cipher.PubKey) string
No reason :)
I just forgot to change signature after merge from mainnet
Although reasons for using address in string forms exists. 
Take a look how  became:
```golang
func (t *memPKTable) RemoteAddr(remotePK cipher.PubKey) *net.TCPAddr {
	rAddr, _ := net.ResolveTCPAddr("tcp", t.entries[remotePK]) // nolint: errcheck
	return rAddr
}
```

2019-08-27 18:00 UTC, ayuryshev commented on pkg/snet/tcp_transport.go
> +func (t *memPKTable) RemotePK(address string) cipher.PubKey {
OK

2019-08-27 18:13 UTC, ayuryshev commented
Fixes requested by Evan - done.
Linter errors and failed tests that were before this PR remains the same.

2019-08-30 07:00 UTC, ayuryshev commented
Remerged with mainnet-milestone-1. Fixed tests for tcp-transport

2019-09-05 11:41 UTC, closed without merging