[WIP] app2 implementation
skycoin/skywire-testnet pull request #543
Opened 2019-08-30 07:28 UTC by Darkren

Fixes #528 

- Added basic structures
- Implemented methods for `HSFrame`

2019-08-30 08:14 UTC, evanlinjin reviewed
:page_facing_up:

2019-08-30 08:14 UTC, evanlinjin commented on pkg/app2/hsframe.go
> +	HSFrameHeaderLength  = 5
Use `Len` instead of `Length`.

2019-08-30 08:14 UTC, evanlinjin commented on pkg/app2/hsframe.go
> +	ErrHSFrameBodyTooLong = errors.New("frame body is too long")
`TooLarge`

2019-09-09 05:14 UTC, evanlinjin requested changes
Good start.

2019-09-09 05:14 UTC, evanlinjin commented on pkg/app2/client.go
> +	logger      *logging.Logger
Let's call this `log` to keep things concise.

2019-09-09 05:14 UTC, evanlinjin commented on pkg/app2/client.go
> +func NewClient(localPK cipher.PubKey, pid ProcID, sockAddr string, l *logging.Logger) (*Client, error) {
Make the `*logging.Logger` as first input. We will try stick to this convention for the rest of our structures.

2019-09-09 05:14 UTC, evanlinjin commented on pkg/app2/client.go
> +func (c *Client) Dial(addr routing.Addr) (net.Conn, error) {
For each of these, I would put the `handshake` step in it's own set of functions.

```golang
func dmsgDialHS(conn net.Conn, pid ProcID, /*other variables needed for handshake*/) error
```

Instead of outputs, we can have pointer inputs.

This way:
1. It improves the testability of the code.
2. It groups each communication exchange together; `dmsgDialHS(), handleDmsgDialHS(), dmsgListenHS(), handleDmsgListenHS()` etc.

2019-09-09 05:14 UTC, evanlinjin commented on pkg/app2/client.go
> +	return stream, nil
We cannot just return `stream` here. We need a structure that knows local/remote dmsg pk and port.

2019-09-09 05:14 UTC, evanlinjin commented on pkg/app2/hsframe.go
> +	HSFrameTypeDMSGListen HSFrameType = 10 + iota
I prefer the following naming convention: `DmsgListenType`, `DmsgListeningType`, `DmsgAcceptType`, etc.

It is a bit less wordy.

2019-09-09 05:14 UTC, evanlinjin commented on pkg/app2/hsframe.go
> +func NewHSFrameDMSGListen(procID ProcID, local routing.Addr) HSFrame {
`NewDmsgListenFrame` would be better. Please follow this convention for the functions below too.

2019-09-09 05:14 UTC, evanlinjin commented on pkg/app2/hsframe.go
> +func (f HSFrame) SetProcID(procID ProcID) {
Not sure if the `Set` member functions for `HSFrame` will be useful. Frames are created as is and is read by the destination.

2019-09-09 05:14 UTC, evanlinjin commented on pkg/app2/listener.go
> +type Listener struct {
Listener needs to handle `Close` in a thread-safe manner. Please use [`snet.Listener`](https://github.com/skycoin/skywire/blob/6439c70ee1ca10d2086c3721fe364800c27c00aa/pkg/snet/stcp/client.go#L56) as an example.

In fact, maybe the entire file will be helpful as it is similar to what we are doing here.

2019-09-09 05:14 UTC, evanlinjin commented on pkg/app2/client.go
> +func (c *Client) Dial(addr routing.Addr) (net.Conn, error) {
It might help to group *pointer inputs* in a structure if we end up with too many inputs (similar to how stdlib `rpc` is done).

2019-09-09 05:14 UTC, evanlinjin commented on pkg/app2/server.go
> +			return errors.Wrap(err, "error creating yamux session")
You forgot a `s.appsMx.Unlock()` here.

2019-09-10 04:54 UTC, evanlinjin commented on pkg/app2/listener.go
> +	hsFrame := NewHSFrameDMSGAccept(l.procID, routing.Loop{
Have you decided to follow what is proposed here: https://discordapp.com/channels/466450852098605059/616123208357380106/618822964917567498

Or have you decided to do something else? Can you define the new communication protocol?

2019-09-10 04:54 UTC, evanlinjin commented on pkg/app2/server.go
> +			localPort := binary.BigEndian.Uint16(hsFrame[HSFrameHeaderLen+HSFramePKLen:])
I hope this is WIP and the logic here will be extracted to it's own functions?

2019-09-16 10:32 UTC, Darkren commented on pkg/app2/client.go
> +	logger      *logging.Logger
Done

2019-09-16 10:32 UTC, Darkren commented on pkg/app2/client.go
> +func NewClient(localPK cipher.PubKey, pid ProcID, sockAddr string, l *logging.Logger) (*Client, error) {
Done

2019-09-18 14:39 UTC, evanlinjin requested changes
Beautifully written code.

Although there is some implementation queries. Specifically, we will need to support multiple *networks* in the future:
- `dmsg`
- `skywire routes`

My comments are mostly regarding this. Hence, you do not need to follow the exact comments, but please take some time to think of an optimal solution.

2019-09-18 14:39 UTC, evanlinjin commented on pkg/app2/server_rpc.go
> +type ServerRPC struct {
Rename to `RPCGateway`.

2019-09-18 14:39 UTC, evanlinjin commented on pkg/app2/server_rpc_client.go
> +type ServerRPCClient interface {
Rename to `RPCClient`.

2019-09-18 14:39 UTC, evanlinjin commented on pkg/app2/client.go
> +func NewClient(localPK cipher.PubKey, pid ProcID, rpc ServerRPCClient, porter *netutil.Porter) *Client {
`porter` does not need to be an input. It can be created here. The `minEph` value will never change.

2019-09-18 14:39 UTC, evanlinjin commented on pkg/app2/client.go
> +func (c *Client) Dial(remote routing.Addr) (net.Conn, error) {
Rename to `DmsgDial`

2019-09-18 14:39 UTC, evanlinjin commented on pkg/app2/client.go
> +func (c *Client) Listen(port routing.Port) (net.Listener, error) {
`DmsgListen`

2019-09-18 14:39 UTC, evanlinjin commented on pkg/app2/client.go
> +func (c *Client) Dial(remote routing.Addr) (net.Conn, error) {
use `remote dmsg.Addr` as we are dialling via `dmsg`.

2019-09-18 14:39 UTC, evanlinjin commented on pkg/app2/conn.go
> +type Conn struct {
for fields `local` and `remote`, have them of `net.Addr` type. That way we can put `dmsg.Addr` or `routing.Addr` (depending on the connection type).

2019-09-18 14:39 UTC, evanlinjin commented on pkg/app2/listener.go
> +type Listener struct {
Maybe rename this to `DmsgListener` or find a way to make it work with all types of `Listener`s (I hope you know what I mean).

2019-09-18 14:39 UTC, evanlinjin commented on pkg/app2/manager.go
> +func (m *manager) getAndRemove(key uint16) (interface{}, error) {
Maybe `pop` will be a better name?

2019-09-18 14:39 UTC, evanlinjin commented on pkg/app2/server_rpc.go
> +func (r *ServerRPC) Dial(remote *routing.Addr, connID *uint16) error {
`DmsgDial` (unless we can make this dial to all sorts).

2019-09-18 14:39 UTC, evanlinjin commented on pkg/app2/server_rpc.go
> +func (r *ServerRPC) Listen(local *routing.Addr, lisID *uint16) error {
`DmsgListen`

2019-09-18 14:39 UTC, evanlinjin commented on pkg/app2/server_rpc.go
> +func (r *ServerRPC) Accept(lisID *uint16, resp *AcceptResp) error {
`DmsgAccept`? Question mark because maybe we can make all these *networks* use the same function.

2019-09-21 17:37 UTC, Darkren commented on pkg/app2/server_rpc.go
> +type ServerRPC struct {
Done

2019-09-21 17:37 UTC, Darkren commented on pkg/app2/server_rpc_client.go
> +type ServerRPCClient interface {
Done

2019-09-21 17:37 UTC, Darkren commented on pkg/app2/client.go
> +func NewClient(localPK cipher.PubKey, pid ProcID, rpc ServerRPCClient, porter *netutil.Porter) *Client {
Done

2019-09-21 17:37 UTC, Darkren commented on pkg/app2/manager.go
> +func (m *manager) getAndRemove(key uint16) (interface{}, error) {
Done

2019-09-23 09:47 UTC, evanlinjin requested changes
Clean code and good work so far. Please review my comments.

2019-09-23 09:47 UTC, evanlinjin commented on pkg/app2/rpc_client.go
> +func (c *rpcCLient) Dial(remote network.Addr) (uint16, error) {
Sorry should have picked this out earlier, but we need to use the ephemeral local address of the actual connection. This should return the local address as well as the identifier.

2019-09-23 09:47 UTC, evanlinjin commented on pkg/app2/rpc_client.go
> +func (c *rpcCLient) Accept(lisID uint16) (uint16, network.Addr, error) {
We need to name the output variables or have a comment that makes it clear that it is the remote address that we are returning here.

2019-09-23 09:47 UTC, evanlinjin commented on pkg/app2/rpc_client.go
> +	if err := c.rpc.Call("Read", &connID, &resp); err != nil {
`(net.Conn).Read(b []byte) (int, error)` relies heavily on the length of the slice `b`. We need to pass this information to the RPC gateway. The request for this RPC call should be of a structure similar to the following:
```golang
type ReadReq struct {
    ConnID uint16
    BLen int // Length of input `b` of `(net.Conn).Read`.
}
```

2019-09-23 09:47 UTC, evanlinjin commented on pkg/app2/client.go
> +	porter *netutil.Porter
Sorry for the changes, but `netutil.Porter` is not the best structure to use here. The local ephemeral keys should be determined by the `network` that we are using, not by `app2.Client`.

Additionally, we need to close all associated `net.Conn`s and `net.Listeners` of this `app2.Client` when it closes. We should keep track of all `connID`s and `lisID`s here and have a `Client.Close` method.

2019-09-23 09:47 UTC, evanlinjin commented on pkg/app2/listener.go
> +// TODO: should unblock all called `Accept`s with errors
This should happen already right? Unless if there is a bug in `dmsg`.

2019-09-23 09:47 UTC, evanlinjin commented on pkg/app2/manager.go
> +type manager struct {
Maybe `idManager` will be a better name?

2019-09-23 09:47 UTC, evanlinjin commented on pkg/app2/network/dmsg_conn.go
> +type DMSGConn struct {
Why is this needed? Can't we just use `*dmsg.Transport` directly?

2019-09-23 09:47 UTC, evanlinjin commented on pkg/app2/rpc_gateway.go
> +	cm  *manager
Let's add some brief comments explaining the fields `lm` and `cm`.

2019-09-23 10:24 UTC, Darkren commented on pkg/app2/network/dmsg_conn.go
> +type DMSGConn struct {
Not really. I used it directly, but since we have a generic `network.Addr` which we return from the server, we also need conns and listeners to return this type underneath the `net.Addr` interface. So, I just had to do this

2019-09-23 10:24 UTC, Darkren commented on pkg/app2/listener.go
> +// TODO: should unblock all called `Accept`s with errors
I'll check it

2019-09-23 10:30 UTC, Darkren commented on pkg/app2/rpc_client.go
> +func (c *rpcCLient) Dial(remote network.Addr) (uint16, error) {
I think that I'd better put it into the `Client.Dial`, since it constructs the actual connection. This way, we'll let `rpcClient` do it's rpc stuff without bothering it with the additional work. I think it's more of a client's responsibility to assign port. What do you think?

2019-09-23 10:32 UTC, Darkren commented on pkg/app2/client.go
> +	porter *netutil.Porter
Hm, but this way, I'll need to do my own porter implementation, right?

2019-09-23 11:18 UTC, Darkren commented on pkg/app2/listener.go
> +// TODO: should unblock all called `Accept`s with errors
No, `Accept` blocks on the RPC `Accept` call. If we close listener, RPC call doesn't unblock, and we can't just close RPC here. Some smart move needs to be here

2019-09-23 11:30 UTC, Darkren commented on pkg/app2/network/dmsg_conn.go
> +type DMSGConn struct {
But it actually messes up some of my logic. Need to think a bit

2019-09-23 15:45 UTC, evanlinjin commented on pkg/app2/rpc_client.go
> +func (c *rpcCLient) Dial(remote network.Addr) (uint16, error) {
> This way, we'll let rpcClient do it's rpc stuff without bothering it with the additional work.

What additional work are you referring to here?

> I think it's more of a client's responsibility to assign port.

I'm not sure if I'm understanding you correctly here. But the main idea of the `app2` library is to perform *network* operations on the visor node. Hence, we want to emulate as much of this interaction as possible, so the entity that uses `app2` sees closely to what they would see if they used `dmsg` or `router` directly. Hence, the both the local and remote addresses of the `dmsg.Transport` between `app2` and `visor`, needs to look the same as between `visor` and the remote `visor`.

Hope that makes sense.

2019-09-23 15:46 UTC, evanlinjin commented on pkg/app2/client.go
> +	porter *netutil.Porter
No, the ephemeral port is decided by the network. At most, we need one or two maps.

2019-09-23 15:49 UTC, evanlinjin commented on pkg/app2/listener.go
> +// TODO: should unblock all called `Accept`s with errors
Given the definition of [`net.Listener`](https://golang.org/pkg/net/#Listener), the following line should unblock when we call `.Close` on the same listener:

https://github.com/skycoin/skywire/blob/e243192a1e1beccb0fcc3658d9ac6a4cb5243094/pkg/app2/rpc_gateway.go#L97

If it doesn't, it means there is a bug with `dmsg`.

2019-09-23 15:50 UTC, evanlinjin commented on pkg/app2/listener.go
> +// TODO: should unblock all called `Accept`s with errors
Is there somewhere else where the `(*RPCGateway).Accept` blocks?

2019-09-23 15:55 UTC, evanlinjin commented on pkg/app2/network/dmsg_conn.go
> +type DMSGConn struct {
The only two things differentiating `dmsg.Transport` and `DMSGConn` is the local and remote addresses. Won't it be better to create a universal structure that can be used with all `net.Conn`s?

For example:

```golang
type WrappedConn struct {
    net.Conn
    lAddr Addr
    rAddr Addr
}

func (c WrappedConn).LocalAddr() net.Addr { return c.lAddr }
func (c WrappedConn).RemoteAddr() net.Conn { return c.rAddr }
```

2019-09-24 05:05 UTC, Darkren commented on pkg/app2/rpc_client.go
> +func (c *rpcCLient) Dial(remote network.Addr) (uint16, error) {
@evanlinjin The additional work is to assign port. `rpcClient`'s only responsibility is to handle RPC calls. The result of the call is being returned to the `Client` which interprets it some way. `Client` constructs `Conn` in my implementation, and that's where the port should be assigned imo

2019-09-24 05:06 UTC, Darkren commented on pkg/app2/client.go
> +	porter *netutil.Porter
@evanlinjin I understand your intention, but I reserve ports through porter. If I remove porter, then I'll need some replacement for it

2019-09-24 05:08 UTC, Darkren commented on pkg/app2/listener.go
> +// TODO: should unblock all called `Accept`s with errors
@evanlinjin yeah, my mistake, everything should be fine

2019-09-24 05:11 UTC, Darkren commented on pkg/app2/network/dmsg_conn.go
> +type DMSGConn struct {
@evanlinjin the problem here is the specific implementation of `net.Conn`. `DMSGConn` wraps transport, so it can assert `dmsg.Addr` type to `net.Addr` and then safely convert `dmsg.Addr` to `network.Addr` also assigning valid network type. If we wrap it the way you suggest, we won't be able to operate on the underlying addr struct. Well, we can if we do a switch over all possible types which can be there. If there's what you'd like to see here, I'll do it this way

2019-09-24 07:50 UTC, evanlinjin commented on pkg/app2/rpc_client.go
> +func (c *rpcCLient) Dial(remote network.Addr) (uint16, error) {
We do not need to assign port. When we call `dmsg.Dial`, we get a local ephemeral port. We should be using this for the associated `app2.Conn`.

```golang
var client *dmsg.Client
conn, err := client.Dial()
if err != nil { panic(err) }
lAddr := conn.LocalAddr()
lPort := lAddr.(dmsg.Addr).Port // Get local ephemeral port here.
```

2019-09-24 07:51 UTC, evanlinjin commented on pkg/app2/client.go
> +	porter *netutil.Porter
We do not need to keep track of ports here. We just need to keep track of `connID`s and `lisID`s so that these can be closed when `app2.Client` closes.

2019-09-24 07:52 UTC, evanlinjin commented on pkg/app2/network/dmsg_conn.go
> +type DMSGConn struct {
> Well, we can if we do a switch over all possible types which can be there. If there's what you'd like to see here, I'll do it this way

Yes please.

2019-09-24 10:15 UTC, Darkren commented on pkg/app2/network/dmsg_conn.go
> +type DMSGConn struct {
@evanlinjin nailed it, please check it out

2019-09-24 10:33 UTC, Darkren commented on pkg/app2/rpc_client.go
> +func (c *rpcCLient) Dial(remote network.Addr) (uint16, error) {
@evanlinjin Done

2019-09-24 11:52 UTC, Darkren commented on pkg/app2/client.go
> +	porter *netutil.Porter
@evanlinjin and this one is done. Just need to adjust tests after all modifications

2019-09-24 14:19 UTC, evanlinjin requested changes
Good stuff. Nearly there.

2019-09-24 14:19 UTC, evanlinjin commented on pkg/app2/network/addr.go
> +func WrapAddr(addr net.Addr) (Addr, error) {
Maybe `ConvertAddr` will be a better name.

2019-09-24 14:19 UTC, evanlinjin commented on pkg/app2/network/addr.go
> +		return Addr{}, errUnknownAddrType
Instead of returning an error, we can panic here to make things easier.

2019-09-24 14:19 UTC, evanlinjin commented on pkg/app2/rpc_client.go
> +func (c *rpcCLient) Dial(remote network.Addr) (connID uint16, assignedPort routing.Port, err error) {
rename `assignedPort` to `localPort`.

2019-09-24 14:19 UTC, evanlinjin commented on pkg/app2/client.go
> +	ok, freePort := c.porter.Reserve(uint16(port), nil)
We don't need to reserve anything here. We should rely on the *network*.

2019-09-24 14:19 UTC, evanlinjin commented on pkg/app2/client.go
> +	porter *netutil.Porter
We should get rid of `porter` entirely.

2019-09-26 12:15 UTC, merged