[WIP] [M2] Implement router2 according to specs
skycoin/skywire-testnet pull request #562
Opened 2019-09-06 14:56 UTC by nkryuchkov

Closes #545

2019-09-08 19:00 UTC, evanlinjin requested changes

2019-09-08 19:00 UTC, evanlinjin commented on pkg/routing/rule.go
> +func (r Rule) SetType(t RuleType) {
Remove the `Set...` member functions. Rules are only created as a whole and should not be modified.

2019-09-11 04:31 UTC, evanlinjin requested changes

2019-09-11 04:31 UTC, evanlinjin commented on pkg/router/route_manager.go
>  	"errors"
I rather get rid of this file completely. The logic here should be moved to `router.Router` and `setup.Client`.

Maybe first ensure the work in `setup` and route finder is done before work on `router`.

2019-09-11 04:31 UTC, evanlinjin commented on pkg/routing/loop.go
In the new implementation, there will be no such thing as a `Loop`.

2019-09-11 04:31 UTC, evanlinjin commented on pkg/routing/table.go
> +func New() Table {
We don't need this. Please remove.

2019-09-11 04:31 UTC, evanlinjin commented on pkg/routing/table.go
> +func NewWithConfig(config Config) Table {
`NewTable`

2019-09-11 04:31 UTC, evanlinjin commented on pkg/routing/table.go
> +type RuleEntry struct {
We don't need this. `Rule` is sufficient.

`Rule` contains both the `RouteID` key and the next route ID (if `ForwardRule` or `IntermediaryForwardRule`).

2019-09-11 04:31 UTC, evanlinjin commented on pkg/routing/table.go
> +func (mt *memTable) DelRules(routeIDs []RouteID) {
`keys []RouteID`

2019-09-11 04:31 UTC, evanlinjin commented on pkg/routing/table.go
> +func (mt *memTable) delRule(routeID RouteID) {
`key RouteID`

2019-09-11 04:31 UTC, evanlinjin commented on pkg/routing/table.go
> +func (mt *memTable) Rule(routeID RouteID) (Rule, error) {
`key RouteID`

2019-09-11 04:31 UTC, evanlinjin commented on pkg/routing/table.go
> +func (mt *memTable) SaveRule(routeID RouteID, rule Rule) error {
`SaveRule(r Rule) error`

2019-09-11 04:31 UTC, evanlinjin commented on pkg/routing/table.go
> +func (mt *memTable) ReserveKey() (RouteID, error) {
`ReserveKey() (key RouteID, err error)`

2019-09-11 04:34 UTC, evanlinjin commented
Good work so far.

Looking at the codebase, it seems that your current approach is to make incremental changes and ensure those changes work with the current codebase.

However, this approach is time consuming as we are doing mostly a rewrite.

Please consider this as a rewrite rather than a refactor.

I recommend prioritising the following:
- Understand the end goal as specified within the specs.
- Ensure the individual components within the specs work.

Later on, once we are sure the components work as expected, we can thing about replacing the current codebase.

2019-09-20 06:31 UTC, evanlinjin requested changes
### Summary of review

Good work so far. I really like what you have done for the routing rules and routing table.

Please ensure setup node is up to spec. Additionally, I think we should use `rpc` instead of defining our own communication protocol for it. Apologies for the change of mind.

I've also mentioned in this review that `router` should be split into `Router` and `SetupGateway`. Where `SetupGateway` has `Router` as a member.

### Additional Comments

Also ensure that the route finder changes are integrated (please talk to @ivcosla ).

Also note that there is no such thing as `Loop` any more.

2019-09-20 06:31 UTC, evanlinjin commented on pkg/router/router.go
> +	rsclient "github.com/skycoin/skywire/pkg/setup/client"
Rename the actual package name to be `"github.com/skycoin/skywire/pkg/route-finder/rsclient"`

2019-09-20 06:31 UTC, evanlinjin commented on pkg/router/router.go
> +	rfclient "github.com/skycoin/skywire/pkg/route-finder/client"
Rename the actual package name to be `"github.com/skycoin/skywire/pkg/routefinder/rfclient"`

2019-09-20 06:31 UTC, evanlinjin commented on pkg/router/router.go
> +	rfclient "github.com/skycoin/skywire/pkg/route-finder/client"
And `github.com/skycoin/skywire/pkg/route-finder` should be `github.com/skycoin/skywire/pkg/routefinder`

2019-09-20 06:31 UTC, evanlinjin commented on pkg/router/router.go
> +	OnLoopClosed  func(loop routing.Loop) error
Why do we need the `OnConfirmLoop` and `OnLoopClosed` members? Can we not call `r.confirmLoop` and `r.loopClosed` directly?

2019-09-20 06:31 UTC, evanlinjin commented on pkg/router/router.go
> +	r.rsc = rsclient.New(n, sl, config.SetupNodes, r.handleSetupConn)
Callbacks are confusing. It will be better to create a new structure named `SetupGateway` which has `Router` as a member. Hence, `SetupGateway` will have member function: `SetupGateway.handleSetupConn` and it's own `SetupGateway.Serve`, removing the need for callbacks.

2019-09-20 06:31 UTC, evanlinjin commented on pkg/setup/client/client.go
> +type Client interface {
It seems as though I was wrong with having a `setup.Client` able to clean up the logic. Let's try the `router.SetupGateway` structure instead (unless you have a better idea?).

2019-09-20 06:31 UTC, evanlinjin commented on pkg/setup/node.go
>  // Node performs routes setup operations over messaging channel.
`setup.Node` still needs to follow spec: https://github.com/watercompany/skywire-specs/blob/master/proposals/router2.md#setup-node-changes

2019-09-20 06:31 UTC, evanlinjin commented on pkg/setup/node.go
>  // Node performs routes setup operations over messaging channel.
Sorry for the change of mind, but instead of defining our own communication protocol for setup, we should use stdlib's `rpc`.

### Instructions

We need two *gateway* structures (which we use to call `(*rpc.Server).Register` with):
- One hosted on `router` that handles requests from `setup`.
- One hosted on `setup` that handles requests from `router`.

So...
- Instead of *Packet Types*, we use member functions for the *gateway* structures.
- Instead of *Packet Body*, we use the inputs of the member functions of the *gateway* structures.

### Examples

Here are some examples for inspiration:
- `app2` implementation: https://github.com/Darkren/skywire/tree/feature/app2/pkg/app2
- `dmsgexec`: https://github.com/SkycoinProject/dmsgexec/blob/master/rpc.go

2019-09-20 06:34 UTC, evanlinjin commented on pkg/router/router.go
> +	r.rsc = rsclient.New(n, sl, config.SetupNodes, r.handleSetupConn)
My point is that the organisation of our structures should be like a tree instead of cyclic. That way, things are easier to understand.

In some cases, callbacks are great, just not here as we will need to read the code in a *cyclic* manner.

2019-09-20 08:57 UTC, aussieboy88 commented on pkg/setup/client/client.go
> +type Client interface {
Client

2019-09-20 11:10 UTC, nkryuchkov commented on pkg/router/router.go
> +	OnLoopClosed  func(loop routing.Loop) error
@evanlinjin I left them for the compatibility with tests. They were modified in tests. However, they will be removed in the next commits.

2019-09-20 14:24 UTC, evanlinjin commented on pkg/router/router.go
> +	OnLoopClosed  func(loop routing.Loop) error
Sounds good.

2019-09-24 07:52 UTC, evanlinjin commented
How's progress?

2019-09-24 07:57 UTC, nkryuchkov commented
@evanlinjin I've just implemented the usage of `net/rpc` instead of own protocol. Integrating the changes with `RouteGroup`'s right now.

2019-09-25 08:24 UTC, evanlinjin requested changes
Good work so far. Please check my comments.

2019-09-25 08:24 UTC, evanlinjin commented on pkg/app/app.go
> +	acceptChan chan []routing.Route
Would it be better to use `routing.RouteDescriptor` here?

2019-09-25 08:24 UTC, evanlinjin commented on pkg/app/packet.go
> +	Route   routing.Route `json:"route"`
Would `routing.RouteDescriptor` here be better?

2019-09-25 08:24 UTC, evanlinjin commented on pkg/router/rpc_server.go
> +func (r *Router) AddRules(rules []routing.Rule, routeIDs *[]routing.RouteID) error {
We should create two structures:
- `Router`
- `RouterGateway`

Where `RouterGateway` has rpc-specific these members, and uses `Router`.

2019-09-25 08:24 UTC, evanlinjin commented on pkg/router/rpc_server.go
> +func (r *Router) AddRules(rules []routing.Rule, routeIDs *[]routing.RouteID) error {
We should also create a `RouterClient` structure,

2019-09-25 08:24 UTC, evanlinjin commented on pkg/setup/idreservoir.go
>  	// 'firstRID' is the first visor's key routeID - this is to be returned.
Remember to update the comments.

2019-09-25 08:24 UTC, evanlinjin commented on pkg/setup/node.go
> +		go sn.rpcSrv.ServeConn(conn.Conn)
We should use a separate `setup.Gateway` structure. This will serve two purposes:

1. We can completely separate setup logic, and the code that only serves as a *gateway* between the setup node and visor node.

2. We can verify requests.

For example, if visor A wants to `CreateRoutes`, we need to verify that the route requested needs to start from A. We can use `setup.Gateway` to store the *context* of the request if we create a new `setup.Gateway` for each request:

```golang
package setup
type Gateway struct {
    reqPK cipher.PubKey // requester's public key
    sn *Node // setup node
}

func (sn *Node) Serve() error {
    for {
        conn, err := sn.dmsgL.AcceptTransport()
        if err != nil { return err }
        rpcS := rpc.NewServer()
        rpcS.RegisterName(&Gateway{reqPK: conn.RemotePK(), sn:sn})
        go rpcS.ServeConn(conn)
    }
}
```

2019-09-25 08:24 UTC, evanlinjin commented on pkg/setup/visor_rpc_helpers.go
> +func (sn *Node) visorAddRules(ctx context.Context, pk cipher.PubKey, rules []routing.Rule) ([]routing.RouteID, error) {
These functions do not need to be members of `setup.Node`. We can just have `*dmsg.Client` as an additional input.

2019-09-25 11:31 UTC, nkryuchkov commented on pkg/app/app.go
> +	acceptChan chan []routing.Route
@evanlinjin It would be, thanks

2019-09-25 11:32 UTC, nkryuchkov commented on pkg/app/packet.go
> +	Route   routing.Route `json:"route"`
@evanlinjin Indeed. Thanks.

2019-09-25 11:34 UTC, nkryuchkov commented on pkg/router/rpc_server.go
> +func (r *Router) AddRules(rules []routing.Rule, routeIDs *[]routing.RouteID) error {
@evanlinjin Good idea

2019-09-25 11:42 UTC, nkryuchkov commented on pkg/setup/visor_rpc_helpers.go
> +func (sn *Node) visorAddRules(ctx context.Context, pk cipher.PubKey, rules []routing.Rule) ([]routing.RouteID, error) {
@evanlinjin 
I made them members of `setup.Node` to use its logger when the closing of router RPC client fails. Creating its own logger for the RPC client didn't seem necessary for me. Anyway, those methods get called from `setup.Node` methods only. 

Do you think it would be better to create its own logger?

2019-09-25 11:43 UTC, nkryuchkov commented on pkg/setup/node.go
> +		go sn.rpcSrv.ServeConn(conn.Conn)
@evanlinjin Good suggestion.

2019-09-25 11:50 UTC, evanlinjin commented on pkg/setup/visor_rpc_helpers.go
> +func (sn *Node) visorAddRules(ctx context.Context, pk cipher.PubKey, rules []routing.Rule) ([]routing.RouteID, error) {
> Do you think it would be better to create its own logger?

No, that would be a little extreme.

Good point, I did not see this. How about having an additional `log logrus.StdLogger` as input?

2019-09-25 11:56 UTC, nkryuchkov commented on pkg/setup/visor_rpc_helpers.go
> +func (sn *Node) visorAddRules(ctx context.Context, pk cipher.PubKey, rules []routing.Rule) ([]routing.RouteID, error) {
@evanlinjin Actually, we can just remove the logging dependency in those functions and just return an error if the closing of client fails. Then we can get rid of `Node` dependency. What do you think?

2019-09-25 12:06 UTC, evanlinjin commented on pkg/setup/visor_rpc_helpers.go
> +func (sn *Node) visorAddRules(ctx context.Context, pk cipher.PubKey, rules []routing.Rule) ([]routing.RouteID, error) {
That can work too. But failing to close shouldn't result in route setup failure later on.

2019-09-25 12:14 UTC, nkryuchkov commented on pkg/setup/visor_rpc_helpers.go
> +func (sn *Node) visorAddRules(ctx context.Context, pk cipher.PubKey, rules []routing.Rule) ([]routing.RouteID, error) {
@evanlinjin I'll think how to do this in the best way. An additional logging argument would be helpful, however I don't like this signatue:
```golang
func visorAddRules(ctx context.Context, log logrus.StdLogger, dmsgC *dmsg.Client, pk cipher.PubKey, rules []routing.Rule) ([]routing.RouteID, error)
`

2019-09-25 13:11 UTC, evanlinjin commented on pkg/setup/visor_rpc_helpers.go
> +func (sn *Node) visorAddRules(ctx context.Context, pk cipher.PubKey, rules []routing.Rule) ([]routing.RouteID, error) {
@nkryuchkov Personally I think it looks okay :sweat_smile: 

Although slightly lengthy, the inputs are easy to understand.

2019-09-25 13:24 UTC, nkryuchkov commented on pkg/setup/visor_rpc_helpers.go
> +func (sn *Node) visorAddRules(ctx context.Context, pk cipher.PubKey, rules []routing.Rule) ([]routing.RouteID, error) {
@evanlinjin I'll do it this way then

2019-10-04 14:49 UTC, evanlinjin requested changes
Very good so far. Please review my comments. Please don't worry about *Making it work as a whole* yet. Just get the components mentioned in the specs implemented. Let's look to merge this (it will be okay if it's not working), but get it compiling. Then let's rebase this to the SkycoinProject org before continuing further.

2019-10-04 14:49 UTC, evanlinjin commented on pkg/app/app.go
> +	acceptChan chan routing.RouteDescriptor
Don't bother working with `app`. We are removing it completely. Actually it will be good if we can remove it now. Please coordinate with @Darkren

2019-10-04 14:49 UTC, evanlinjin commented on pkg/router/gateway.go
> +		r.router.accept <- rules
We need to create a function such as: `router.IntroduceRules` or something similar. This is to allow for thread-safety when shutting down.

2019-10-04 14:49 UTC, evanlinjin commented on pkg/router/router.go
> +var DefaultDialOptions = &DialOptions{
I would prefer if this was a function instead: `func DefaultDialOptions() DialOptions`. This way the values become immutable.

2019-10-04 14:49 UTC, evanlinjin commented on pkg/router/router.go
> +	req := routing.BidirectionalRoute{
Nice name!

2019-10-04 14:49 UTC, evanlinjin commented on pkg/router/router.go
> +	rules := <-r.accept
We may need a `done` chan to go along with this. Probably need to give some thought on the close logic.

2019-10-04 14:49 UTC, evanlinjin commented on pkg/router/router.go
> +		routeID, err := r.rt.ReserveKey()
It might be better to change `(routing.Table).ReserveKey()` to `(routing.Table).ReserveKeys(n int)`.

2019-10-04 14:49 UTC, evanlinjin commented on pkg/router/router.go
> +	rules := <-r.accept
Or work some magic using `context.Context`.

2019-10-04 14:49 UTC, evanlinjin commented on pkg/router/routerclient/client.go
> +func (c *Client) AddEdgeRules(ctx context.Context, rules routing.EdgeRules) (bool, error) {
If we use the deadline functions of the underlying `net.Conn` (`dmsg` that is), we won't need to use `context.Context`. Just some food for thought... Not sure which is best. But lets use `context.Context` for now.

2019-10-04 14:49 UTC, evanlinjin commented on pkg/setup/gateway.go
> +	ctx := context.Background()
We might need to have a context with timeout. Let's say 1 minute just to be safe? Is there a better way to do timeout?

2019-10-04 14:49 UTC, evanlinjin commented on pkg/setup/idreservoir.go
> +func (idr *idReservoir) GenerateRules(forward, reverse routing.Route) (forwardRules, consumeRules map[cipher.PubKey]routing.Rule, intermediaryRules RulesMap, err error) {
I know that routes are working in a very different manner in m2, but there was a bug in m1 (fixed here: https://github.com/SkycoinProject/skywire-mainnet/commit/7eccea4421cfad767c21e0c4955f221f9f329106). Let me know if this was causing an issue, or if we are fine. Thanks!

2019-10-04 14:49 UTC, evanlinjin commented on pkg/setup/gateway.go
> +func (g *Gateway) DialRouteGroup(route routing.BidirectionalRoute, rules *routing.EdgeRules) (failure error) {
This looks clean. However, I would prefer if most of the logic is elsewhere, and the `Gateway` structure acts as just a *gateway*.

2019-10-04 14:49 UTC, evanlinjin commented on pkg/setup/setupclient/client.go
> +	nodes []cipher.PubKey
We need to make clear (probably via comments) that this refers to setup node PKs.

2019-10-04 15:46 UTC, nkryuchkov commented on pkg/router/router.go
> +	req := routing.BidirectionalRoute{
@evanlinjin thanks!

2019-10-08 17:14 UTC, nkryuchkov commented on pkg/setup/idreservoir.go
> +func (idr *idReservoir) GenerateRules(forward, reverse routing.Route) (forwardRules, consumeRules map[cipher.PubKey]routing.Rule, intermediaryRules RulesMap, err error) {
@evanlinjin It's fixed in the new implementation.

2019-10-08 17:16 UTC, nkryuchkov commented on pkg/setup/gateway.go
> +	ctx := context.Background()
@evanlinjin 1 minute is a good idea, I'll think if there's a better way.

2019-10-11 10:34 UTC, nkryuchkov commented on pkg/app/app.go
> +	acceptChan chan routing.RouteDescriptor
@Darkren will remove it in his PR

2019-10-15 09:25 UTC, evanlinjin requested changes

2019-10-15 09:25 UTC, evanlinjin commented on pkg/app2/rpc_gateway.go
> -	"github.com/pkg/errors"
So have we decided against using `pkg/errors` for m2?

2019-10-15 09:25 UTC, evanlinjin commented on pkg/router/route_group.go
> +	// The following fields are used for writing:
We need to reorganize these comments/fields.

2019-10-15 09:25 UTC, evanlinjin commented on pkg/router/route_group.go
> +
Should we check if the RouteGroup is closed here, to avoid writing when the RouteGroup closes.

2019-10-15 09:26 UTC, evanlinjin commented
I haven't said much. The code looks good. We just need to ensure it works.

2019-10-15 09:56 UTC, nkryuchkov commented on pkg/app2/rpc_gateway.go
> -	"github.com/pkg/errors"
The `github.com/pkg/errors` is not related to the standard library. The new error features in 1.13 were added to the `errors` package. 

The `github.com/pkg/errors` was used in `app2` only, so the usage of `errors` and `github.com/pkg/errors` was mixed. I decided to make it consistent in this PR. 

I think we should go with the standard library `errors` and use more of its features but within another PR.

2019-10-15 09:58 UTC, nkryuchkov commented on pkg/router/route_group.go
> +
@evanlinjin You're right, thanks!

2019-11-14 15:12 UTC, nkryuchkov commented
Replaced by https://github.com/SkycoinProject/skywire-mainnet/pull/51

2019-11-14 15:12 UTC, closed without merging