Feature/route finder single route
skycoin/skywire-testnet pull request #568
Opened 2019-09-10 17:43 UTC by ivcosla

Closes #567

2019-09-11 03:51 UTC, evanlinjin requested changes
Good work. However, how can we test this?

2019-09-11 03:51 UTC, evanlinjin commented on pkg/route-finder/client/client.go
> +func (c *apiClient) FindRoutes(ctx context.Context, rts [][2]cipher.PubKey, opts *RouteOptions) ([][]routing.Route, error) {
Have the following changes:
- Create a new type `type Path []routing.Hop`
- Use the following as the output: `map[[2]cipher.PubKey][]routing.Path`

2019-09-11 07:54 UTC, ivcosla commented
> Good work. However, how can we test this?

We can run integration tests, no matter which one as long as we test that routes are being created. They are working on my tests. Basically run the following:
 1) checkout both repositories (skywire and skywire-services) to `feature/route-finder-single-route`
 2) on skywire-services run `make integration-build`; `make integration-run-generic`; `make integration-startup`
 3) run `curl --data  {'"recipient":"'$PK_A'", "message":"Hello Joe!"}' -X POST  $CHAT_C`, if such message arrives to visor_a it's succesful 

For unit testing the API however I think it would be better to write them on the server side.

2019-09-23 09:49 UTC, evanlinjin commented
@nkryuchkov please give this a review and see if we can merge this into your work so far. Thanks!

2019-09-23 10:21 UTC, nkryuchkov approved these changes
Great job!

2019-09-23 10:21 UTC, nkryuchkov commented on pkg/routing/route.go
> +	res.WriteString(":") // nolint
Although both `WriteString` and `Write` of `bytes.Buffer` always return `nil` as an error, I would explicitly check for an error here and below.

2019-09-23 10:35 UTC, nkryuchkov commented
@evanlinjin I've already merged it into my work

2019-09-24 08:11 UTC, evanlinjin commented
> @evanlinjin I've already merged it into my work

Should we close this PR then?

2019-09-24 08:14 UTC, nkryuchkov commented
@evanlinjin If it's to be merged in my work only, then yes.

2019-09-24 08:17 UTC, evanlinjin commented
Already merged into #562

2019-09-24 08:17 UTC, closed without merging